
#include "ogl_names.h"

OGL_FUNC_DESC oglNames[] = {
    // Miscellaneous
    FUNC_DECL1(VOID_TYPE, "glClear", BITMASK_TYPE),
    FUNC_DECL4(VOID_TYPE, "glClearColor", CLAMPF_TYPE, CLAMPF_TYPE, CLAMPF_TYPE, CLAMPF_TYPE),
    FUNC_DECL1(VOID_TYPE, "glClearIndex", FLOAT_TYPE),

    FUNC_DECL4(VOID_TYPE, "glColorMask", BOOLEAN_TYPE, BOOLEAN_TYPE, BOOLEAN_TYPE, BOOLEAN_TYPE),
    FUNC_DECL1(VOID_TYPE, "glIndexMask", UINT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glAlphaFunc", ENUM_TYPE, CLAMPF_TYPE),

    FUNC_DECL2(VOID_TYPE, "glBlendFunc", ENUM_TYPE, ENUM_TYPE),
    FUNC_DECL1(VOID_TYPE, "glLogicOp", ENUM_TYPE),
    FUNC_DECL1(VOID_TYPE, "glCullFace", ENUM_TYPE),

    FUNC_DECL1(VOID_TYPE, "glFrontFace", ENUM_TYPE),
    FUNC_DECL1(VOID_TYPE, "glPointSize", FLOAT_TYPE),
    FUNC_DECL1(VOID_TYPE, "glLineWidth", FLOAT_TYPE),

    FUNC_DECL2(VOID_TYPE, "glLineStipple", INT_TYPE, USHORT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glPolygonMode", ENUM_TYPE, ENUM_TYPE),
    FUNC_DECL2(VOID_TYPE, "glPolygonOffset", FLOAT_TYPE, FLOAT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glPolygonStipple", UBYTE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glEdgeFlag", BOOLEAN_TYPE),
    FUNC_DECL1(VOID_TYPE, "glEdgeFlagv", BOOLEAN_PTR_TYPE),

    FUNC_DECL4(VOID_TYPE, "glScissor", INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glClipPlane", ENUM_TYPE, DOUBLE_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glGetClipPlane", ENUM_TYPE, DOUBLE_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glDrawBuffer", ENUM_TYPE),
    FUNC_DECL1(VOID_TYPE, "glReadBuffer", ENUM_TYPE),
    FUNC_DECL1(VOID_TYPE, "glEnable", ENUM_TYPE),

    FUNC_DECL1(VOID_TYPE, "glDisable", ENUM_TYPE),
    FUNC_DECL1(BOOLEAN_TYPE, "glIsEnabled", ENUM_TYPE),

    V11_FUNC_DECL1(BOOLEAN_TYPE, "glEnableClientState", ENUM_TYPE),
    V11_FUNC_DECL1(BOOLEAN_TYPE, "glDisableClientState", ENUM_TYPE),

    FUNC_DECL2(VOID_TYPE, "glGetBooleanv", ENUM_TYPE, BOOLEAN_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glGetDoublev", ENUM_TYPE, DOUBLE_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glGetFloatv", ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glGetIntegerv", ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glPushAttrib", BITMASK_TYPE),
    FUNC_DECL0(VOID_TYPE, "glPopAttrib"),

    V11_FUNC_DECL1(BOOLEAN_TYPE, "glPushClientAttrib", BITFIELD_TYPE),
    V11_FUNC_DECL0(BOOLEAN_TYPE, "glPopClientAttrib"),

    FUNC_DECL1(INT_TYPE, "glRenderMode", ENUM_TYPE),
    FUNC_DECL0(ENUM_TYPE, "glGetError"),
    FUNC_DECL1(UBYTE_PTR_TYPE, "glGetString", ENUM_TYPE),

    FUNC_DECL0(VOID_TYPE, "glFinish"),
    FUNC_DECL0(VOID_TYPE, "glFlush"),
    FUNC_DECL2(VOID_TYPE, "glHint", ENUM_TYPE, DOUBLE_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glClearDepth", CLAMPD_TYPE),
    FUNC_DECL1(VOID_TYPE, "glDepthFunc", ENUM_TYPE),
    FUNC_DECL1(VOID_TYPE, "glDepthMask", BOOLEAN_TYPE),
    FUNC_DECL2(VOID_TYPE, "glDepthRange", CLAMPD_TYPE, CLAMPD_TYPE),

    FUNC_DECL4(VOID_TYPE, "glClearAccum", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glDepthRange", ENUM_TYPE, FLOAT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glMatrixMode", ENUM_TYPE),

    FUNC_DECL6(VOID_TYPE, "glOrtho", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL6(VOID_TYPE, "glFrustum", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),

    FUNC_DECL4(VOID_TYPE, "glViewport", INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE),

    FUNC_DECL0(VOID_TYPE, "glPushMatrix"),
    FUNC_DECL0(VOID_TYPE, "glPopMatrix"),
    FUNC_DECL0(VOID_TYPE, "glLoadIdentity"),

    FUNC_DECL1(VOID_TYPE, "glLoadMatrixd", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glLoadMatrixf", FLOAT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glMultMatrixd", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glMultMatrixf", FLOAT_PTR_TYPE),

    FUNC_DECL4(VOID_TYPE, "glRotated", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glRotatef", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),

    FUNC_DECL4(VOID_TYPE, "glScaled", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glScalef", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),

    FUNC_DECL4(VOID_TYPE, "glTranslated", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glTranslatef", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),

    FUNC_DECL1(BOOLEAN_TYPE, "glIsList", UINT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glDeleteLists", UINT_TYPE, SIZEI_TYPE),
    FUNC_DECL1(UINT_TYPE, "glGenLists", SIZEI_TYPE),
    FUNC_DECL2(VOID_TYPE, "glNewList", UINT_TYPE, ENUM_TYPE),
    FUNC_DECL0(VOID_TYPE, "glEndList"),
    FUNC_DECL1(VOID_TYPE, "glCallList", UINT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glCallLists", SIZEI_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glListBase", UINT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glBegin", ENUM_TYPE),
    FUNC_DECL0(VOID_TYPE, "glEnd"),

    FUNC_DECL2(VOID_TYPE, "glVertex2d", DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL2(VOID_TYPE, "glVertex2f", FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glVertex2i", INT_TYPE, INT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glVertex2s", SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL3(VOID_TYPE, "glVertex3d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glVertex3f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glVertex3i", INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glVertex3s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL4(VOID_TYPE, "glVertex4d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glVertex4f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glVertex4i", INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glVertex4s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glVertex2dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex2fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex2iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex2sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glVertex3dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex3fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex3iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex3sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glVertex4dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex4fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex4iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glVertex4sv", SHORT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glNormal3b", BYTE_TYPE, BYTE_TYPE, BYTE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glNormal3d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glNormal3f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glNormal3i", INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glNormal3s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glNormal3bv", BYTE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glNormal3dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glNormal3fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glNormal3iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glNormal3sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glIndexd", DOUBLE_TYPE),
    FUNC_DECL1(VOID_TYPE, "glIndexf", FLOAT_TYPE),
    FUNC_DECL1(VOID_TYPE, "glIndexi", INT_TYPE),
    FUNC_DECL1(VOID_TYPE, "glIndexs", SHORT_TYPE),
    V11_FUNC_DECL1(VOID_TYPE, "glIndexub", UBYTE_TYPE),

    FUNC_DECL1(VOID_TYPE, "glIndexdv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glIndexfv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glIndexiv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glIndexsv", SHORT_PTR_TYPE),
    V11_FUNC_DECL1(VOID_TYPE, "glIndexubv", UBYTE_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glColor3b", BYTE_TYPE, BYTE_TYPE, BYTE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColor3d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColor3f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColor3i", INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColor3s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColor3ub", UBYTE_TYPE, UBYTE_TYPE, UBYTE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColor3ui", UINT_TYPE, UINT_TYPE, UINT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColor3us", USHORT_TYPE, USHORT_TYPE, USHORT_TYPE),

    FUNC_DECL4(VOID_TYPE, "glColor4b", BYTE_TYPE, BYTE_TYPE, BYTE_TYPE, BYTE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColor4d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColor4f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColor4i", INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColor4s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColor4ub", UBYTE_TYPE, UBYTE_TYPE, UBYTE_TYPE, UBYTE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColor4ui", UINT_TYPE, UINT_TYPE, UINT_TYPE, UINT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColor4us", USHORT_TYPE, USHORT_TYPE, USHORT_TYPE, USHORT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glColor3bv", BYTE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor3dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor3fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor3iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor3sv", SHORT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor3ubv", UBYTE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor3uiv", UINT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor3usv", USHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glColor4bv", BYTE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor4dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor4fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor4iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor4sv", SHORT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor4ubv", UBYTE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor4uiv", UINT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glColor4usv", USHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glTexCoord2d", DOUBLE_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord2f", FLOAT_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord2i", INT_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord2s", SHORT_TYPE),

    FUNC_DECL2(VOID_TYPE, "glTexCoord2d", DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL2(VOID_TYPE, "glTexCoord2f", FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glTexCoord2i", INT_TYPE, INT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glTexCoord2s", SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL3(VOID_TYPE, "glTexCoord3d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexCoord3f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexCoord3i", INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexCoord3s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL4(VOID_TYPE, "glTexCoord4d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glTexCoord4f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glTexCoord4i", INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glTexCoord4s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glTexCoord1dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord1fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord1iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord1sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glTexCoord2dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord2fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord2iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord2sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glTexCoord3dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord3fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord3iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord3sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glTexCoord4dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord4fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord4iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glTexCoord4sv", SHORT_PTR_TYPE),

    FUNC_DECL2(VOID_TYPE, "glRasterPos2d", DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL2(VOID_TYPE, "glRasterPos2f", FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glRasterPos2i", INT_TYPE, INT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glRasterPos2s", SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL3(VOID_TYPE, "glRasterPos3d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glRasterPos3f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glRasterPos3i", INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glRasterPos3s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL4(VOID_TYPE, "glRasterPos4d", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glRasterPos4f", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glRasterPos4i", INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glRasterPos4s", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL1(VOID_TYPE, "glRasterPos2dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos2fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos2iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos2sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glRasterPos3dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos3fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos3iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos3sv", SHORT_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glRasterPos4dv", DOUBLE_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos4fv", FLOAT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos4iv", INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glRasterPos4sv", SHORT_PTR_TYPE),

    FUNC_DECL4(VOID_TYPE, "glRectd", DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    FUNC_DECL4(VOID_TYPE, "glRectf", FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glRecti", INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE),
    FUNC_DECL4(VOID_TYPE, "glRects", SHORT_TYPE, SHORT_TYPE, SHORT_TYPE, SHORT_TYPE),

    FUNC_DECL2(VOID_TYPE, "glRectdv", DOUBLE_PTR_TYPE, DOUBLE_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glRectfv", FLOAT_PTR_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glRectiv", INT_PTR_TYPE, INT_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glRectsv", SHORT_PTR_TYPE, SHORT_PTR_TYPE),
    // Vertex Arrays  (1.1)
    FUNC_DECL4(VOID_TYPE, "glVertexPointer", INT_TYPE, ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glNormalPointer", ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    FUNC_DECL4(VOID_TYPE, "glColorPointer", INT_TYPE, ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glIndexPointer", ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    FUNC_DECL4(VOID_TYPE, "glTexCoordPointer", INT_TYPE, ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glEdgeFlagPointer", SIZEI_TYPE, VOID_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glGetPointerv", ENUM_TYPE, VOID_VOID_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glArrayElement", INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glDrawArrays", ENUM_TYPE, INT_TYPE, SIZEI_TYPE),
    FUNC_DECL4(VOID_TYPE, "glDrawElements", ENUM_TYPE, SIZEI_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glInterleavedArrays", ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),

    FUNC_DECL1(VOID_TYPE, "glShadeModel", ENUM_TYPE),

    FUNC_DECL3(VOID_TYPE, "glLightf", ENUM_TYPE, ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glLighti", ENUM_TYPE, ENUM_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glLightfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glLightiv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetLightfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetLightiv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL2(VOID_TYPE, "glLightModelf", ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glLightModeli", ENUM_TYPE, INT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glLightModelfv", ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glLightModeliv", ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glMaterialf", ENUM_TYPE, ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glMateriali", ENUM_TYPE, ENUM_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glMaterialfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glMaterialiv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetMaterialfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetMaterialiv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL2(VOID_TYPE, "glColorMaterial", ENUM_TYPE, ENUM_TYPE),
    // Raster functions
    FUNC_DECL2(VOID_TYPE, "glPixelZoom", FLOAT_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glPixelStoref", ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glPixelStorei", ENUM_TYPE, INT_TYPE),

    FUNC_DECL2(VOID_TYPE, "glPixelTransferf", ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL2(VOID_TYPE, "glPixelTransferi", ENUM_TYPE, INT_TYPE),

    FUNC_DECL3(VOID_TYPE, "glPixelMapfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glPixelMapuiv", ENUM_TYPE, ENUM_TYPE, UINT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glPixelMapusv", ENUM_TYPE, ENUM_TYPE, USHORT_PTR_TYPE),

    FUNC_DECL2(VOID_TYPE, "glGetPixelMapfv", ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glGetPixelMapuiv", ENUM_TYPE, UINT_PTR_TYPE),
    FUNC_DECL2(VOID_TYPE, "glGetPixelMapusv", ENUM_TYPE, USHORT_PTR_TYPE),

    FUNC_DECL7(VOID_TYPE, "glBitmap", SIZEI_TYPE, SIZEI_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, FLOAT_TYPE, UBYTE_PTR_TYPE),
    FUNC_DECL7(VOID_TYPE, "glReadPixels", INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),

    FUNC_DECL5(VOID_TYPE, "glDrawPixels", SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL5(VOID_TYPE, "glCopyPixels", INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE),
    // Stenciling
    FUNC_DECL3(VOID_TYPE, "glStencilFunc", ENUM_TYPE, INT_TYPE, UINT_TYPE),
    FUNC_DECL1(VOID_TYPE, "glStencilMask", UINT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glStencilOp", ENUM_TYPE, ENUM_TYPE, ENUM_TYPE),
    FUNC_DECL1(VOID_TYPE, "glClearStencil", INT_TYPE),
    // Texture mapping
    FUNC_DECL3(VOID_TYPE, "glTexGend", ENUM_TYPE, ENUM_TYPE, DOUBLE_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexGenf", ENUM_TYPE, ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexGeni", ENUM_TYPE, ENUM_TYPE, INT_TYPE),

    FUNC_DECL3(VOID_TYPE, "glTexGendv", ENUM_TYPE, ENUM_TYPE, DOUBLE_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexGenfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexGeniv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glGetTexGendv", ENUM_TYPE, ENUM_TYPE, DOUBLE_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetTexGenfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetTexGeniv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glTexEnvf", ENUM_TYPE, ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexEnvi", ENUM_TYPE, ENUM_TYPE, INT_TYPE),

    FUNC_DECL3(VOID_TYPE, "glTexEnvfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexEnviv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glGetTexEnvfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetTexEnviv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glTexParameterf", ENUM_TYPE, ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexParameteri", ENUM_TYPE, ENUM_TYPE, INT_TYPE),

    FUNC_DECL3(VOID_TYPE, "glTexParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glTexParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glGetTexParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetTexParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL4(VOID_TYPE, "glGetTexLevelParameterfv", ENUM_TYPE, INT_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL4(VOID_TYPE, "glGetTexLevelParameteriv", ENUM_TYPE, INT_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL8(VOID_TYPE, "glTexImage1D", ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, INT_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL9(VOID_TYPE, "glTexImage2D", ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, INT_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL5(VOID_TYPE, "glGetTexImage", ENUM_TYPE, INT_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),

    V11_FUNC_DECL2(VOID_TYPE, "glGenTextures", SIZEI_TYPE, UINT_PTR_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glDeleteTextures", SIZEI_TYPE, UINT_PTR_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glBindTexture", ENUM_TYPE, UINT_TYPE),

    V11_FUNC_DECL3(VOID_TYPE, "glPrioritizeTextures", SIZEI_TYPE, UINT_PTR_TYPE, CLAMPF_PTR_TYPE),
    V11_FUNC_DECL3(BOOLEAN_TYPE, "glAreTexturesResident", SIZEI_TYPE, UINT_PTR_TYPE, BOOLEAN_PTR_TYPE),
    V11_FUNC_DECL1(BOOLEAN_TYPE, "glIsTexture", UINT_TYPE),

    V11_FUNC_DECL7(VOID_TYPE, "glTexSubImage1D", ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),

    V11_FUNC_DECL9(VOID_TYPE, "glTexSubImage2D", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),

    V11_FUNC_DECL7(VOID_TYPE, "glCopyTexImage1D", ENUM_TYPE, INT_TYPE, ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, INT_TYPE),

    V11_FUNC_DECL8(VOID_TYPE, "glCopyTexImage2D", ENUM_TYPE, INT_TYPE, ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, INT_TYPE),

    V11_FUNC_DECL6(VOID_TYPE, "glCopyTexSubImage1D", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE),

    V11_FUNC_DECL8(VOID_TYPE, "glCopyTexSubImage2D", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE),
    // Evaluators
    V11_FUNC_DECL6(VOID_TYPE, "glMap1d", ENUM_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, INT_TYPE, INT_TYPE, DOUBLE_PTR_TYPE),
    V11_FUNC_DECL6(VOID_TYPE, "glMap1f", ENUM_TYPE, FLOAT_TYPE, FLOAT_TYPE, INT_TYPE, INT_TYPE, FLOAT_PTR_TYPE),

    V11_FUNC_DECL10(VOID_TYPE, "glMap1d", ENUM_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, INT_TYPE, INT_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, INT_TYPE, INT_TYPE, DOUBLE_PTR_TYPE),
    V11_FUNC_DECL10(VOID_TYPE, "glMap1f", ENUM_TYPE, FLOAT_TYPE, FLOAT_TYPE, INT_TYPE, INT_TYPE, FLOAT_TYPE, FLOAT_TYPE, INT_TYPE, INT_TYPE, FLOAT_PTR_TYPE),

    V11_FUNC_DECL3(VOID_TYPE, "glGetMapdv", ENUM_TYPE, ENUM_TYPE, DOUBLE_PTR_TYPE),
    V11_FUNC_DECL3(VOID_TYPE, "glGetMapfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    V11_FUNC_DECL3(VOID_TYPE, "glGetMapiv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    V11_FUNC_DECL1(VOID_TYPE, "glEvalCoord1d", DOUBLE_TYPE),
    V11_FUNC_DECL1(VOID_TYPE, "glEvalCoord1f", FLOAT_TYPE),

    V11_FUNC_DECL1(VOID_TYPE, "glEvalCoord1dv", DOUBLE_PTR_TYPE),
    V11_FUNC_DECL1(VOID_TYPE, "glEvalCoord1fv", FLOAT_PTR_TYPE),

    V11_FUNC_DECL2(VOID_TYPE, "glEvalCoord2d", DOUBLE_TYPE, DOUBLE_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glEvalCoord2f", FLOAT_TYPE, FLOAT_TYPE),

    V11_FUNC_DECL1(VOID_TYPE, "glEvalCoord2dv", DOUBLE_PTR_TYPE),
    V11_FUNC_DECL1(VOID_TYPE, "glEvalCoord2fv", FLOAT_PTR_TYPE),

    V11_FUNC_DECL3(VOID_TYPE, "glMapGrid1d", INT_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    V11_FUNC_DECL3(VOID_TYPE, "glMapGrid1f", INT_TYPE, FLOAT_TYPE, FLOAT_TYPE),

    V11_FUNC_DECL6(VOID_TYPE, "glMapGrid2d", INT_TYPE, DOUBLE_TYPE, DOUBLE_TYPE, INT_TYPE, DOUBLE_TYPE, DOUBLE_TYPE),
    V11_FUNC_DECL6(VOID_TYPE, "glMapGrid2f", INT_TYPE, FLOAT_TYPE, FLOAT_TYPE, INT_TYPE, FLOAT_TYPE, FLOAT_TYPE),

    V11_FUNC_DECL1(VOID_TYPE, "glEvalPoint1", INT_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glEvalPoint2", INT_TYPE, INT_TYPE),

    V11_FUNC_DECL3(VOID_TYPE, "glEvalMesh1", ENUM_TYPE, INT_TYPE, INT_TYPE),
    V11_FUNC_DECL5(VOID_TYPE, "glEvalMesh2", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE),

    // Fog
    V11_FUNC_DECL2(VOID_TYPE, "glFogf", ENUM_TYPE, FLOAT_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glFogi", ENUM_TYPE, INT_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glFogfv", ENUM_TYPE, FLOAT_PTR_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glFogiv", ENUM_TYPE, INT_PTR_TYPE),

    // Selection and Feedback
    V11_FUNC_DECL3(VOID_TYPE, "glFeedbackBuffer", SIZEI_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    V11_FUNC_DECL1(VOID_TYPE, "glPassThrough", FLOAT_TYPE),
    V11_FUNC_DECL2(VOID_TYPE, "glSelectBuffer", SIZEI_TYPE, UINT_PTR_TYPE),
    V11_FUNC_DECL0(VOID_TYPE, "glInitNames"),
    V11_FUNC_DECL1(VOID_TYPE, "glLoadName", UINT_TYPE),
    V11_FUNC_DECL1(VOID_TYPE, "glPushName", UINT_TYPE),
    V11_FUNC_DECL0(VOID_TYPE, "glPopName"),

    // OpenGL 1.2
    V12_FUNC_DECL6(VOID_TYPE, "glPopName", ENUM_TYPE, UINT_TYPE, UINT_TYPE, SIZEI_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    V12_FUNC_DECL10(VOID_TYPE, "glTexImage3D", ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, SIZEI_TYPE, INT_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    V12_FUNC_DECL11(VOID_TYPE, "glTexSubImage3D", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    V12_FUNC_DECL9(VOID_TYPE, "glCopyTexSubImage3D", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, ENUM_TYPE, ENUM_TYPE),
    // typedef void (APIENTRYP PFNGLDRAWRANGEELEMENTSPROC) (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices);
    // typedef void (APIENTRYP PFNGLTEXIMAGE3DPROC) (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
    // typedef void (APIENTRYP PFNGLTEXSUBIMAGE3DPROC) (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels);
    // typedef void (APIENTRYP PFNGLCOPYTEXSUBIMAGE3DPROC) (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
    //
    // GL_ARB_imaging
    FUNC_DECL6(VOID_TYPE, "glColorTable", ENUM_TYPE, ENUM_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL6(VOID_TYPE, "glColorSubTable", ENUM_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColorTableParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glColorTableParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),

    FUNC_DECL5(VOID_TYPE, "glColorTableParameterfv", ENUM_TYPE, SIZEI_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE),
    FUNC_DECL5(VOID_TYPE, "glCopyColorTable", ENUM_TYPE, ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE),
    FUNC_DECL4(VOID_TYPE, "glGetColorTable", ENUM_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetColorTableParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetColorTableParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),
    FUNC_DECL1(VOID_TYPE, "glBlendEquation", ENUM_TYPE),

    FUNC_DECL4(VOID_TYPE, "glBlendColor", CLAMPF_TYPE, CLAMPF_TYPE, CLAMPF_TYPE, CLAMPF_TYPE),
    FUNC_DECL4(VOID_TYPE, "glHistogram", ENUM_TYPE, SIZEI_TYPE, ENUM_TYPE, BOOLEAN_TYPE),
    FUNC_DECL1(VOID_TYPE, "glResetHistogram", ENUM_TYPE),
    FUNC_DECL5(VOID_TYPE, "glGetHistogram", ENUM_TYPE, BOOLEAN_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetHistogramParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetHistogramParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glMinmax", ENUM_TYPE, ENUM_TYPE, BOOLEAN_TYPE),
    FUNC_DECL1(VOID_TYPE, "glResetMinmax", ENUM_TYPE),
    FUNC_DECL5(VOID_TYPE, "glGetMinmax", ENUM_TYPE, BOOLEAN_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetMinmaxParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetMinmaxParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL6(VOID_TYPE, "glConvolutionFilter1D", ENUM_TYPE, ENUM_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL7(VOID_TYPE, "glConvolutionFilter2D", ENUM_TYPE, ENUM_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glConvolutionParameterf", ENUM_TYPE, ENUM_TYPE, FLOAT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glConvolutionParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),

    FUNC_DECL3(VOID_TYPE, "glConvolutionParameteri", ENUM_TYPE, ENUM_TYPE, INT_TYPE),
    FUNC_DECL3(VOID_TYPE, "glConvolutionParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL5(VOID_TYPE, "glCopyConvolutionFilter1D", ENUM_TYPE, ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE),
    FUNC_DECL6(VOID_TYPE, "glCopyConvolutionFilter2D", ENUM_TYPE, ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE),

    FUNC_DECL4(VOID_TYPE, "glGetConvolutionFilter", ENUM_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetConvolutionParameterfv", ENUM_TYPE, ENUM_TYPE, FLOAT_PTR_TYPE),
    FUNC_DECL3(VOID_TYPE, "glGetConvolutionParameteriv", ENUM_TYPE, ENUM_TYPE, INT_PTR_TYPE),

    FUNC_DECL8(VOID_TYPE, "glSeparableFilter2D", ENUM_TYPE, ENUM_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE, VOID_PTR_TYPE),
    FUNC_DECL6(VOID_TYPE, "glGetSeparableFilter", ENUM_TYPE, ENUM_TYPE, ENUM_TYPE, VOID_PTR_TYPE, VOID_PTR_TYPE, VOID_PTR_TYPE),

    // OpenGL 1.3
    V13_FUNC_DECL1(VOID_TYPE, "glActiveTexture", ENUM_TYPE),
    V13_FUNC_DECL1(VOID_TYPE, "glClientActiveTexture", ENUM_TYPE),
    V13_FUNC_DECL7(VOID_TYPE, "glCompressedTexImage1D", ENUM_TYPE, INT_TYPE, ENUM_TYPE, SIZEI_TYPE, INT_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    V13_FUNC_DECL8(VOID_TYPE, "glCompressedTexImage2D", ENUM_TYPE, INT_TYPE, ENUM_TYPE, SIZEI_TYPE, SIZEI_TYPE, INT_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),

    V13_FUNC_DECL7(VOID_TYPE, "glCompressedTexSubImage1D", ENUM_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    V13_FUNC_DECL9(VOID_TYPE, "glCompressedTexSubImage2D", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),
    V13_FUNC_DECL11(VOID_TYPE, "glCompressedTexSubImage3D", ENUM_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, INT_TYPE, SIZEI_TYPE, SIZEI_TYPE, SIZEI_TYPE, ENUM_TYPE, SIZEI_TYPE, VOID_PTR_TYPE),

    V13_FUNC_DECL3(VOID_TYPE, "glGetCompressedTexImage", ENUM_TYPE, INT_TYPE, VOID_PTR_TYPE),

    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1d", ENUM_TYPE, DOUBLE_TYPE),
    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1dv", ENUM_TYPE, DOUBLE_PTR_TYPE),

    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1f", ENUM_TYPE, FLOAT_TYPE),
    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1fv", ENUM_TYPE, FLOAT_PTR_TYPE),

    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1i", ENUM_TYPE, INT_TYPE),
    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1iv", ENUM_TYPE, INT_PTR_TYPE),

    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1s", ENUM_TYPE, SHORT_TYPE),
    V13_FUNC_DECL2(VOID_TYPE, "glMultiTexCoord1sv", ENUM_TYPE, SHORT_PTR_TYPE),
};
/*
GLAPI void GLAPIENTRY glMultiTexCoord2d( GLenum target, GLdouble s, GLdouble t );

GLAPI void GLAPIENTRY glMultiTexCoord2dv( GLenum target, const GLdouble *v );

GLAPI void GLAPIENTRY glMultiTexCoord2f( GLenum target, GLfloat s, GLfloat t );

GLAPI void GLAPIENTRY glMultiTexCoord2fv( GLenum target, const GLfloat *v );

GLAPI void GLAPIENTRY glMultiTexCoord2i( GLenum target, GLint s, GLint t );

GLAPI void GLAPIENTRY glMultiTexCoord2iv( GLenum target, const GLint *v );

GLAPI void GLAPIENTRY glMultiTexCoord2s( GLenum target, GLshort s, GLshort t );

GLAPI void GLAPIENTRY glMultiTexCoord2sv( GLenum target, const GLshort *v );

GLAPI void GLAPIENTRY glMultiTexCoord3d( GLenum target, GLdouble s, GLdouble t, GLdouble r );

GLAPI void GLAPIENTRY glMultiTexCoord3dv( GLenum target, const GLdouble *v );

GLAPI void GLAPIENTRY glMultiTexCoord3f( GLenum target, GLfloat s, GLfloat t, GLfloat r );

GLAPI void GLAPIENTRY glMultiTexCoord3fv( GLenum target, const GLfloat *v );

GLAPI void GLAPIENTRY glMultiTexCoord3i( GLenum target, GLint s, GLint t, GLint r );

GLAPI void GLAPIENTRY glMultiTexCoord3iv( GLenum target, const GLint *v );

GLAPI void GLAPIENTRY glMultiTexCoord3s( GLenum target, GLshort s, GLshort t, GLshort r );

GLAPI void GLAPIENTRY glMultiTexCoord3sv( GLenum target, const GLshort *v );

GLAPI void GLAPIENTRY glMultiTexCoord4d( GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q );

GLAPI void GLAPIENTRY glMultiTexCoord4dv( GLenum target, const GLdouble *v );

GLAPI void GLAPIENTRY glMultiTexCoord4f( GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q );

GLAPI void GLAPIENTRY glMultiTexCoord4fv( GLenum target, const GLfloat *v );

GLAPI void GLAPIENTRY glMultiTexCoord4i( GLenum target, GLint s, GLint t, GLint r, GLint q );

GLAPI void GLAPIENTRY glMultiTexCoord4iv( GLenum target, const GLint *v );

GLAPI void GLAPIENTRY glMultiTexCoord4s( GLenum target, GLshort s, GLshort t, GLshort r, GLshort q );

GLAPI void GLAPIENTRY glMultiTexCoord4sv( GLenum target, const GLshort *v );


GLAPI void GLAPIENTRY glLoadTransposeMatrixd( const GLdouble m[16] );

GLAPI void GLAPIENTRY glLoadTransposeMatrixf( const GLfloat m[16] );

GLAPI void GLAPIENTRY glMultTransposeMatrixd( const GLdouble m[16] );

GLAPI void GLAPIENTRY glMultTransposeMatrixf( const GLfloat m[16] );

GLAPI void GLAPIENTRY glSampleCoverage( GLclampf value, GLboolean invert );


typedef void (APIENTRYP PFNGLACTIVETEXTUREPROC) (GLenum texture);
typedef void (APIENTRYP PFNGLSAMPLECOVERAGEPROC) (GLclampf value, GLboolean invert);
typedef void (APIENTRYP PFNGLCOMPRESSEDTEXIMAGE3DPROC) (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data);
typedef void (APIENTRYP PFNGLCOMPRESSEDTEXIMAGE2DPROC) (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data);
typedef void (APIENTRYP PFNGLCOMPRESSEDTEXIMAGE1DPROC) (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data);
typedef void (APIENTRYP PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC) (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data);
typedef void (APIENTRYP PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC) (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data);
typedef void (APIENTRYP PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC) (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data);
typedef void (APIENTRYP PFNGLGETCOMPRESSEDTEXIMAGEPROC) (GLenum target, GLint level, GLvoid *img);
*/
/*
GL_ARB_multitexture (ARB extension 1 and OpenGL 1.2.1)

GLAPI void GLAPIENTRY glActiveTextureARB(GLenum texture);
GLAPI void GLAPIENTRY glClientActiveTextureARB(GLenum texture);
GLAPI void GLAPIENTRY glMultiTexCoord1dARB(GLenum target, GLdouble s);
GLAPI void GLAPIENTRY glMultiTexCoord1dvARB(GLenum target, const GLdouble *v);
GLAPI void GLAPIENTRY glMultiTexCoord1fARB(GLenum target, GLfloat s);
GLAPI void GLAPIENTRY glMultiTexCoord1fvARB(GLenum target, const GLfloat *v);
GLAPI void GLAPIENTRY glMultiTexCoord1iARB(GLenum target, GLint s);
GLAPI void GLAPIENTRY glMultiTexCoord1ivARB(GLenum target, const GLint *v);
GLAPI void GLAPIENTRY glMultiTexCoord1sARB(GLenum target, GLshort s);
GLAPI void GLAPIENTRY glMultiTexCoord1svARB(GLenum target, const GLshort *v);
GLAPI void GLAPIENTRY glMultiTexCoord2dARB(GLenum target, GLdouble s, GLdouble t);
GLAPI void GLAPIENTRY glMultiTexCoord2dvARB(GLenum target, const GLdouble *v);
GLAPI void GLAPIENTRY glMultiTexCoord2fARB(GLenum target, GLfloat s, GLfloat t);
GLAPI void GLAPIENTRY glMultiTexCoord2fvARB(GLenum target, const GLfloat *v);
GLAPI void GLAPIENTRY glMultiTexCoord2iARB(GLenum target, GLint s, GLint t);
GLAPI void GLAPIENTRY glMultiTexCoord2ivARB(GLenum target, const GLint *v);
GLAPI void GLAPIENTRY glMultiTexCoord2sARB(GLenum target, GLshort s, GLshort t);
GLAPI void GLAPIENTRY glMultiTexCoord2svARB(GLenum target, const GLshort *v);
GLAPI void GLAPIENTRY glMultiTexCoord3dARB(GLenum target, GLdouble s, GLdouble t, GLdouble r);
GLAPI void GLAPIENTRY glMultiTexCoord3dvARB(GLenum target, const GLdouble *v);
GLAPI void GLAPIENTRY glMultiTexCoord3fARB(GLenum target, GLfloat s, GLfloat t, GLfloat r);
GLAPI void GLAPIENTRY glMultiTexCoord3fvARB(GLenum target, const GLfloat *v);
GLAPI void GLAPIENTRY glMultiTexCoord3iARB(GLenum target, GLint s, GLint t, GLint r);
GLAPI void GLAPIENTRY glMultiTexCoord3ivARB(GLenum target, const GLint *v);
GLAPI void GLAPIENTRY glMultiTexCoord3sARB(GLenum target, GLshort s, GLshort t, GLshort r);
GLAPI void GLAPIENTRY glMultiTexCoord3svARB(GLenum target, const GLshort *v);
GLAPI void GLAPIENTRY glMultiTexCoord4dARB(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
GLAPI void GLAPIENTRY glMultiTexCoord4dvARB(GLenum target, const GLdouble *v);
GLAPI void GLAPIENTRY glMultiTexCoord4fARB(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
GLAPI void GLAPIENTRY glMultiTexCoord4fvARB(GLenum target, const GLfloat *v);
GLAPI void GLAPIENTRY glMultiTexCoord4iARB(GLenum target, GLint s, GLint t, GLint r, GLint q);
GLAPI void GLAPIENTRY glMultiTexCoord4ivARB(GLenum target, const GLint *v);
GLAPI void GLAPIENTRY glMultiTexCoord4sARB(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q);
GLAPI void GLAPIENTRY glMultiTexCoord4svARB(GLenum target, const GLshort *v);

typedef void (APIENTRYP PFNGLACTIVETEXTUREARBPROC) (GLenum texture);
typedef void (APIENTRYP PFNGLCLIENTACTIVETEXTUREARBPROC) (GLenum texture);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1DARBPROC) (GLenum target, GLdouble s);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1DVARBPROC) (GLenum target, const GLdouble *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1FARBPROC) (GLenum target, GLfloat s);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1FVARBPROC) (GLenum target, const GLfloat *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1IARBPROC) (GLenum target, GLint s);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1IVARBPROC) (GLenum target, const GLint *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1SARBPROC) (GLenum target, GLshort s);
typedef void (APIENTRYP PFNGLMULTITEXCOORD1SVARBPROC) (GLenum target, const GLshort *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2DARBPROC) (GLenum target, GLdouble s, GLdouble t);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2DVARBPROC) (GLenum target, const GLdouble *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2FARBPROC) (GLenum target, GLfloat s, GLfloat t);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2FVARBPROC) (GLenum target, const GLfloat *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2IARBPROC) (GLenum target, GLint s, GLint t);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2IVARBPROC) (GLenum target, const GLint *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2SARBPROC) (GLenum target, GLshort s, GLshort t);
typedef void (APIENTRYP PFNGLMULTITEXCOORD2SVARBPROC) (GLenum target, const GLshort *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3DARBPROC) (GLenum target, GLdouble s, GLdouble t, GLdouble r);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3DVARBPROC) (GLenum target, const GLdouble *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3FARBPROC) (GLenum target, GLfloat s, GLfloat t, GLfloat r);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3FVARBPROC) (GLenum target, const GLfloat *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3IARBPROC) (GLenum target, GLint s, GLint t, GLint r);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3IVARBPROC) (GLenum target, const GLint *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3SARBPROC) (GLenum target, GLshort s, GLshort t, GLshort r);
typedef void (APIENTRYP PFNGLMULTITEXCOORD3SVARBPROC) (GLenum target, const GLshort *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4DARBPROC) (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4DVARBPROC) (GLenum target, const GLdouble *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4FARBPROC) (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4FVARBPROC) (GLenum target, const GLfloat *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4IARBPROC) (GLenum target, GLint s, GLint t, GLint r, GLint q);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4IVARBPROC) (GLenum target, const GLint *v);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4SARBPROC) (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q);
typedef void (APIENTRYP PFNGLMULTITEXCOORD4SVARBPROC) (GLenum target, const GLshort *v);
*/
OGL_FUNC_DESC *getNames(int *pSize)
{
    if (pSize != 0)
    {
        *pSize = sizeof(oglNames) / sizeof(OGL_FUNC_DESC);
    }
    return oglNames;
}