#ifndef __PASULI_COMPILATION_CONFIGURATION_FILE_
#define __PASULI_COMPILATION_CONFIGURATION_FILE_

// For MS compiler
#define PASULI_COMPILER_MSVC 1
// For GCC compiler collection
#define PASULI_COMPILER_GCC 2

// Used compiler
#define PASULI_COMPILER PASULI_COMPILER_GCC

//Debuging
#define PASULI_DEBUG_MODE 1
// ??
#define USE_ID_IN_PSLDD 0
// If not 0, then the ID will be assigned in the evaluation function
#define USE_ID_IN_PASULI_FUNCTION 0

/////////////////////////
/////////////////////////
/////////////////////////

#if (USE_ID_IN_PSLDD != 0)
#define PSLDD_ID(X) X,
#else
#define PSLDD_ID(X)
#endif

#if (USE_ID_IN_PASULI_FUNCTION != 0)
#define PASULI_SET_TYPE_ID(X) pO->_ID = X;
#else
#define PASULI_SET_TYPE_ID(X)
#endif

//#define COMPILE_SURFACES				1
#define COMPILE_DEF_DESC_SURFACES 1
#define COMPILE_DESC_SURFACES 1
#define COMPILE_NAMES_SURFACES 1
#define COMPILE_POS_SURFACES 1
#define COMPILE_DERIV_U_SURFACES 1
#define COMPILE_DERIV_V_SURFACES 1
#define COMPILE_NORMAL_SURFACES 1
#define COMPILE_DERIV2_U_SURFACES 1
#define COMPILE_DERIV2_V_SURFACES 1
#define COMPILE_DERIV_UV_SURFACES 1
#define COMPILE_DESC_DERIV_U_SURFACES 1
#define COMPILE_DESC_DERIV_V_SURFACES 1
#define COMPILE_DESC_NORMAL_SURFACES 1
#define COMPILE_DESC_DERIV2_U_SURFACES 1
#define COMPILE_DESC_DERIV2_V_SURFACES 1
#define COMPILE_DESC_DERIV_UV_SURFACES 1

//#define COMPILE_CYLINDER			1
#define COMPILE_DEF_DESC_CYLINDER 1
#define COMPILE_DESC_CYLINDER 1
#define COMPILE_NAMES_CYLINDER 1
#define COMPILE_POS_CYLINDER 1
#define COMPILE_DERIV_U_CYLINDER 1
#define COMPILE_DERIV_V_CYLINDER 1
#define COMPILE_NORMAL_CYLINDER 1
#define COMPILE_DERIV2_U_CYLINDER 1
#define COMPILE_DERIV2_V_CYLINDER 1
#define COMPILE_DERIV_UV_CYLINDER 1
#define COMPILE_DESC_DERIV_U_CYLINDER 1
#define COMPILE_DESC_DERIV_V_CYLINDER 1
#define COMPILE_DESC_NORMAL_CYLINDER 1
#define COMPILE_DESC_DERIV2_U_CYLINDER 1
#define COMPILE_DESC_DERIV2_V_CYLINDER 1
#define COMPILE_DESC_DERIV_UV_CYLINDER 1

//#define COMPILE_FRUITS					1
#define COMPILE_DEF_DESC_FRUITS 1
#define COMPILE_DESC_FRUITS 1
#define COMPILE_NAMES_FRUITS 1
#define COMPILE_POS_FRUITS 1
#define COMPILE_DERIV_U_FRUITS 1
#define COMPILE_DERIV_V_FRUITS 1
#define COMPILE_NORMAL_FRUITS 1
#define COMPILE_DERIV2_U_FRUITS 1
#define COMPILE_DERIV2_V_FRUITS 1
#define COMPILE_DERIV_UV_FRUITS 1
#define COMPILE_DESC_DERIV_U_FRUITS 1
#define COMPILE_DESC_DERIV_V_FRUITS 1
#define COMPILE_DESC_NORMAL_FRUITS 1
#define COMPILE_DESC_DERIV2_U_FRUITS 1
#define COMPILE_DESC_DERIV2_V_FRUITS 1
#define COMPILE_DESC_DERIV_UV_FRUITS 1

//#define COMPILE_SHELLS					1
#define COMPILE_DEF_DESC_SHELLS 1
#define COMPILE_DESC_SHELLS 1
#define COMPILE_NAMES_SHELLS 1
#define COMPILE_POS_SHELLS 1
#define COMPILE_DERIV_U_SHELLS 1
#define COMPILE_DERIV_V_SHELLS 1
#define COMPILE_NORMAL_SHELLS 1
#define COMPILE_DERIV2_U_SHELLS 1
#define COMPILE_DERIV2_V_SHELLS 1
#define COMPILE_DERIV_UV_SHELLS 1
#define COMPILE_DESC_DERIV_U_SHELLS 1
#define COMPILE_DESC_DERIV_V_SHELLS 1
#define COMPILE_DESC_NORMAL_SHELLS 1
#define COMPILE_DESC_DERIV2_U_SHELLS 1
#define COMPILE_DESC_DERIV2_V_SHELLS 1
#define COMPILE_DESC_DERIV_UV_SHELLS 1

//#define COMPILE_SPHERE					1
#define COMPILE_DEF_DESC_SPHERE 1
#define COMPILE_DESC_SPHERE 1
#define COMPILE_NAMES_SPHERE 1
#define COMPILE_POS_SPHERE 1
#define COMPILE_DERIV_U_SPHERE 1
#define COMPILE_DERIV_V_SPHERE 1
#define COMPILE_NORMAL_SPHERE 1
#define COMPILE_DERIV2_U_SPHERE 1
#define COMPILE_DERIV2_V_SPHERE 1
#define COMPILE_DERIV_UV_SPHERE 1
#define COMPILE_DESC_DERIV_U_SPHERE 1
#define COMPILE_DESC_DERIV_V_SPHERE 1
#define COMPILE_DESC_NORMAL_SPHERE 1
#define COMPILE_DESC_DERIV2_U_SPHERE 1
#define COMPILE_DESC_DERIV2_V_SPHERE 1
#define COMPILE_DESC_DERIV_UV_SPHERE 1

//#define COMPILE_SPIRAL					1
#define COMPILE_NAMES_SPIRAL 1
#define COMPILE_DEF_DESC_SPIRAL 1
#define COMPILE_DESC_SPIRAL 1
#define COMPILE_POS_SPIRAL 1
#define COMPILE_DERIV_U_SPIRAL 1
#define COMPILE_DERIV_V_SPIRAL 1
#define COMPILE_NORMAL_SPIRAL 1
#define COMPILE_DERIV2_U_SPIRAL 1
#define COMPILE_DERIV2_V_SPIRAL 1
#define COMPILE_DERIV_UV_SPIRAL 1
#define COMPILE_DESC_DERIV_U_SPIRAL 1
#define COMPILE_DESC_DERIV_V_SPIRAL 1
#define COMPILE_DESC_NORMAL_SPIRAL 1
#define COMPILE_DESC_DERIV2_U_SPIRAL 1
#define COMPILE_DESC_DERIV2_V_SPIRAL 1
#define COMPILE_DESC_DERIV_UV_SPIRAL 1

//#define COMPILE_TORUS					1
#define COMPILE_NAMES_TORUS 1
#define COMPILE_DEF_DESC_TORUS 1
#define COMPILE_DESC_TORUS 1
#define COMPILE_POS_TORUS 1
#define COMPILE_DERIV_U_TORUS 1
#define COMPILE_DERIV_V_TORUS 1
#define COMPILE_NORMAL_TORUS 1
#define COMPILE_DERIV2_U_TORUS 1
#define COMPILE_DERIV2_V_TORUS 1
#define COMPILE_DERIV_UV_TORUS 1
#define COMPILE_DESC_DERIV_U_TORUS 1
#define COMPILE_DESC_DERIV_V_TORUS 1
#define COMPILE_DESC_NORMAL_TORUS 1
#define COMPILE_DESC_DERIV2_U_TORUS 1
#define COMPILE_DESC_DERIV2_V_TORUS 1
#define COMPILE_DESC_DERIV_UV_TORUS 1

//////////////////////////////////////////
#define USE_PLANE 1
#define USE_BOHEMIAN_DOME_SURFACE 1
#define USE_BOYS_SURFACE 1
#define USE_CROSS_CUP 1
#define USE_DINI_SURFACE 1
#define USE_ENNEPER_SURFACE 1
#define USE_HANDKERCHIEF 1
#define USE_KLEIN_BOTTLE_SURFACE 1
#define USE_MOEBIUS_BAND 1
#define USE_MONKEY_SADDLE 1
#define USE_PLUECKER_CONOID 1
#define USE_ROMAN_SURFACE 1
#define USE_SHOE_SURFACE 1
#define USE_SINE_SURFACE 1
#define USE_STEINBACH_SCREW 1
#define USE_WHITNEY_UMBRELLA 1
#define USE_CATENOID 1
#define USE_HELICOID 1
#define USE_PARABOLOID 1
#define USE_HYPERBOLIC_HELICOID 1
#define USE_FUNNEL 1
#define USE_TRACTROID 1
#define USE_CATALANS_SURFACE 1
#define USE_HYPERBOLOID 1
#define USE_HENNEBERGS_SURFACE 1
#define USE_SWALLOW_SURFACE 1
#define USE_WALLIS_CONICAL_SURFACE 1
#define USE_MAEDERS_OWL 1
#define USE_RICHMOND_SURFACE 1
#define USE_SCHERK_SURFACE 1
#define USE_COSINE_SURFACE 1
#define USE_EIGHT_SURFACE 1
#define USE_JET_SURFACE 1
#define USE_DROP 1
#define USE_TRIAXIAL_TEARDROP 1
#define USE_PILLOW_SHAPE 1
#define USE_FISH_SURFACE 1
#define USE_HORN 1
#define USE_BENT_HORNS 1
#define USE_HYPERBOLIC_OCTAHEDRON 1
#define USE_PSEUDO_CROSS_CAP 1
#define USE_CRESENT 1
#define USE_STILETTO_SURFACE 1
#define USE_KUENS_SURFACE 1
#define USE_TREFOIL_KNOTS 1
#define USE_TRANGULOID_TREFOIL 1
#define USE_CROWN 1
#define USE_TWISTED_PIPE_SURFACE 1
#define USE_LOOP 1
#define USE_DUPIN_CYCLIDE 1
#define USE_GUIMARD_SURFACE 1
#define USE_MENNS_SURFACE 1
#define USE_MILK_BAG 1
#define USE_SADDLE_TORUS 1
#define USE_TRIAXIAL_TRITORUS 1
#define USE_VERRILL_SURFACE 1
#define USE_ZINDLERS_CONOID 1
#define USE_FOLIUM 1
#define USE_LEMNISCAPE 1
#define USE_TRIPLE_POINT_TWIST 1
#define USE_TRASHCAN 1
#define USE_SPRING1 1
#define USE_SPRING2 1
#define USE_CONE 1
#define USE_EGG 1
#define USE_ISOLATOR 1
#define USE_HYPERBOLIC_PARABOLOID 1
#define USE_DROP_SURFACE 1
#define USE_FACING_SNAIL 1
#define USE_PAPER_BAG 1
#define USE_JEENER_KLEIN_SURFACE 1
#define USE_BONAN_JEENER_KLEIN_SURFACE 1
#define USE_KLEIN_CYCLOID 1
#define USE_DOUBLE_CONE 1
#define USE_HOLE_DISC 1
#define USE_PISOT_TRIAXIAL 1
#define USE_TRIAXIAL_HEXATORUS 1
#define USE_TWISTED_HEART 1
#define USE_HOLE_DISCUS 1
#define USE_DISC 1
#define USE_WAVES 1
#define USE_SINE_WAVE 1
#define USE_COSINE_WAVE 1
#define USE_SPIRAL_WAVE 1
#define USE_BELL 1
#define USE_BELL_POLAR 1
#define USE_BELL_WAVE 1
#define USE_SOUCOUPOID 1
#define USE_ENNEPER_SURFACE_POLAR 1
#define USE_SINE_CONE 1
#define USE_SPINNER 1
#define USE_FRESNEL 1
#define USE_TREFOIL_KNOTS2 1
#define USE_BOW_CURVE 1
#define USE_TRIPLE_CORK_SCREW1 1
#define USE_TRIPLE_CORK_SCREW2 1
#define USE_TRIPLE_CORK_SCREW3 1
#define USE_BICORN_SURFACE 1
#define USE_PIRIFORM_SURFACE 1
#define USE_KAPPA_SURFACE 1
#define USE_BULLET_NOSE 1
#define USE_SIEVERT_SURFACE 1
#define USE_COSINE_SURFACE2 1

//CYLINDER SURFACES
#define USE_CYLINDER 1
#define USE_EPIZYKLOID_CYLINDER 1
#define USE_HYPOZYKLOID_CYLINDER 1
#define USE_LEMNISKATE_CYLINDER 1
#define USE_STROPHOIDE_CYLINDER 1
#define USE_ZISSOIDE_CYLINDER 1
#define USE_VERSIERA_AGNESI_CYLINDER 1
#define USE_GAUSS_CYLINDER 1

//FRUITS SURFACES
#define USE_KIDNEY_SURFACE 1
#define USE_APPLE_SURFACE 1
#define USE_APPLE2_SURFACE 1
#define USE_LEMON_SURFACE 1

// Shells
#define USE_CORNUCOPIA 1
#define USE_SNAIL 1
#define USE_SEASHELL 1
#define USE_SNAIL_SURFACE 1
#define USE_SNAILS 1
#define USE_PSEUDOHELICERAS_SUBCATENATUM 1
#define USE_ASTROCERAS 1
#define USE_BELLEROPHINA 1
#define USE_EUHOPLITES 1
#define USE_NAUTILUS 1
#define USE_NATICA_STELLATA 1
#define USE_MYA_ARENARIA 1

// Sphere surfaces
#define USE_SPHERE 1
#define USE_ELLIPSOID 1
#define USE_SPHERE_V 1
#define USE_SPHERE_UV 1
#define USE_PSEUDOSPHERE 1
#define USE_TWISTED_SPHERE 1
#define USE_OPEN_SPHERE 1
#define USE_WAVE_SPHERE 1

// Spiral surfaces
#define USE_ARCHIMEDIC_SPIRAL 1
#define USE_HYPERBOLIC_SPIRAL 1
#define USE_FERMAT_SPIRAL 1
#define USE_TANH_SPIRAL 1
#define USE_LOG_SPIRAL 1

// TORUS SURFACES
#define USE_TORUS 1
#define USE_EIGHT_TORUS 1
#define USE_ELLIPTIC_TORUS 1
#define USE_SADDLE_TORUS 1
#define USE_ANTISYMMETRIC_TORUS 1
#define USE_TWISTED_EIGHT_TORUS 1
#define USE_UMBILLIC_TORUS 1
#define USE_BRAIDED_TORUS 1
#define USE_LIMPET_TORUS 1
#define USE_STRANGLED_TORUS 1
#define USE_ASTROID_TORUS 1
#define USE_TRICUSPOID_TORUS_1 1
#define USE_TRICUSPOID_TORUS_2 1
#define USE_NETHROID_TORUS_1 1
#define USE_NETHROID_TORUS_2 1
#define USE_LEMNISKATE_TORUS_1 1
#define USE_LEMNISKATE_TORUS_2 1
#define USE_EPIZYKLOID_TORUS_1 1
#define USE_EPIZYKLOID_TORUS_2 1
#define USE_HYPOZYKLOID_TORUS_1 1
#define USE_HYPOZYKLOID_TORUS_2 1
#define USE_PIRIFORM_TORUS_1 1
#define USE_PIRIFORM_TORUS_2 1
#define USE_BICORN_TORUS_1 1
#define USE_BICORN_TORUS_2 1
#define USE_CARDIOID_TORUS_1 1
#define USE_CARDIOID_TORUS_2 1
#define USE_CASSINIAN_OVAL_TORUS_1 1
#define USE_CASSINIAN_OVAL_TORUS_2 1
#define USE_GERONO_LEMNISKATE_TORUS_1 1
#define USE_GERONO_LEMNISKATE_TORUS_2 1
#define USE_CURLY_TORUS_1 1
#define USE_CURLY_TORUS_2 1
#define USE_SPIRAL_TORUS 1
#define USE_TORUS_KNOT 1
#define USE_GEAR_TORUS 1
#define USE_WAVE_TORUS 1

#endif
