
#include <stdlib.h>
#include "pasuli_cfg.h"
#include "pasuli_repository.h"

unsigned int numberOfPasuli = 100;

typedef struct
{
	unsigned char id;
	double constant;
} DefaultConstants1;

typedef struct
{
	unsigned char id;
	double constants[2];
} DefaultConstants2;

typedef struct
{
	unsigned char id;
	double constants[3];
} DefaultConstants3;

typedef struct
{
	unsigned char id;
	double constants[4];
} DefaultConstants4;

#define PASULI_CONSTANT1_ENTRY(ID, C) \
	{                                 \
		ID, C                         \
	}
#define PASULI_CONSTANT2_ENTRY(ID, C1, C2) \
	{                                      \
		ID, { C1, C2 }                     \
	}
#define PASULI_CONSTANT3_ENTRY(ID, C1, C2, C3) \
	{                                          \
		ID, { C1, C2, C3 }                     \
	}

DefaultConstants1 forSingleConstant[] = {
	PASULI_CONSTANT1_ENTRY(PLANE, 0),

};

DefaultConstants2 for2Constants[] = {

};

DefaultConstants3 for3Constants[] = {

};

DefaultConstants4 for4Constants[] = {

};

#define ID_AND_LENGTH(ID, L) \
	{                        \
		ID, L                \
	}

#define CONST_1(C) C
#define CONST_2(C1, C2) C1, C2
#define CONST_3(C1, C2, C3) C1, C2, C3
#define CONST_4(C1, C2, C3, C4) C1, C2, C3, C4

unsigned char id_and_length[][2] = {
	ID_AND_LENGTH(PLANE, 1),
	ID_AND_LENGTH(BOHEMIAN_DOME_SURFACE, 3),
	ID_AND_LENGTH(BOYS_SURFACE, 0),
	ID_AND_LENGTH(CROSS_CUP, 0),
	//
	ID_AND_LENGTH(DINI_SURFACE, 2),
	ID_AND_LENGTH(ENNEPER_SURFACE, 0),
	ID_AND_LENGTH(HANDKERCHIEF, 0),
	ID_AND_LENGTH(KLEIN_BOTTLE_SURFACE, 3),
	//
	ID_AND_LENGTH(MOEBIUS_BAND, 1),
	ID_AND_LENGTH(MONKEY_SADDLE, 0),
	ID_AND_LENGTH(PLUECKER_CONOID, 0),
	ID_AND_LENGTH(ROMAN_SURFACE, 0),
	//
	ID_AND_LENGTH(SHOE_SURFACE, 0),
	ID_AND_LENGTH(SINE_SURFACE, 0),
	ID_AND_LENGTH(STEINBACH_SCREW, 0),
	ID_AND_LENGTH(WHITNEY_UMBRELLA, 0),
	//
	ID_AND_LENGTH(CATENOID, 1),
	ID_AND_LENGTH(HELICOID, 1),
	ID_AND_LENGTH(PARABOLOID, 2),
	ID_AND_LENGTH(HYPERBOLIC_HELICOID, 1),
	//
	ID_AND_LENGTH(FUNNEL, 0),
	ID_AND_LENGTH(TRACTROID, 0),
	ID_AND_LENGTH(CATALANS_SURFACE, 0),
	ID_AND_LENGTH(HYPERBOLOID, 2),
	//
	ID_AND_LENGTH(HENNEBERGS_SURFACE, 0),
	ID_AND_LENGTH(SWALLOW_SURFACE, 0),
	ID_AND_LENGTH(WALLIS_CONICAL_SURFACE, 3),
	ID_AND_LENGTH(MAEDERS_OWL, 0),
	//
	ID_AND_LENGTH(RICHMOND_SURFACE, 0),
	ID_AND_LENGTH(SCHERK_SURFACE, 1),
	ID_AND_LENGTH(COSINE_SURFACE, 0),
	ID_AND_LENGTH(EIGHT_SURFACE, 0),
	//
	ID_AND_LENGTH(JET_SURFACE, 0),
	ID_AND_LENGTH(DROP, 2),
	ID_AND_LENGTH(TRIAXIAL_TEARDROP, 0),
	ID_AND_LENGTH(PILLOW_SHAPE, 1),
	//
	ID_AND_LENGTH(FISH_SURFACE, 0),
	ID_AND_LENGTH(HORN, 3),
	ID_AND_LENGTH(BENT_HORNS, 0),
	ID_AND_LENGTH(HYPERBOLIC_OCTAHEDRON, 0),
	//
	ID_AND_LENGTH(PSEUDO_CROSS_CAP, 0),
	ID_AND_LENGTH(CRESENT, 3),
	ID_AND_LENGTH(STILETTO_SURFACE, 0),
	ID_AND_LENGTH(KUENS_SURFACE, 0),
	//
	ID_AND_LENGTH(TREFOIL_KNOTS, 2),
	ID_AND_LENGTH(TRANGULOID_TREFOIL, 0),
	ID_AND_LENGTH(CROWN, 0),
	ID_AND_LENGTH(TWISTED_PIPE_SURFACE, 0),
	//
	ID_AND_LENGTH(LOOP, 0),
	ID_AND_LENGTH(DUPIN_CYCLIDE, 4),
	ID_AND_LENGTH(GUIMARD_SURFACE, 3),
	ID_AND_LENGTH(MENNS_SURFACE, 1),
	//
	ID_AND_LENGTH(MILK_BAG, 1),
	ID_AND_LENGTH(TRIAXIAL_TRITORUS, 0),
	ID_AND_LENGTH(VERRILL_SURFACE, 0),
	ID_AND_LENGTH(ZINDLERS_CONOID, 1),
	//
	ID_AND_LENGTH(FOLIUM, 0),
	ID_AND_LENGTH(LEMNISCAPE, 0),
	ID_AND_LENGTH(TRIPLE_POINT_TWIST, 1),
	ID_AND_LENGTH(TRASHCAN, 2),
	//
	ID_AND_LENGTH(SPRING1, 4),
	ID_AND_LENGTH(SPRING2, 3),
	ID_AND_LENGTH(CONE, 1),
	ID_AND_LENGTH(EGG, 3),
	//
	ID_AND_LENGTH(ISOLATOR, 3),
	ID_AND_LENGTH(HYPERBOLIC_PARABOLOID, 0),
	ID_AND_LENGTH(FACING_SNAIL, 1),
	ID_AND_LENGTH(PAPER_BAG, 2),
	//
	ID_AND_LENGTH(JEENER_KLEIN_SURFACE, 3),
	ID_AND_LENGTH(BONAN_JEENER_KLEIN_SURFACE, 2),
	ID_AND_LENGTH(KLEIN_CYCLOID, 3),
	ID_AND_LENGTH(DOUBLE_CONE, 0),
	//
	ID_AND_LENGTH(HOLE_DISC, 0),
	ID_AND_LENGTH(PISOT_TRIAXIAL, 0),
	ID_AND_LENGTH(TRIAXIAL_HEXATORUS, 0),
	ID_AND_LENGTH(TWISTED_HEART, 0),
	//
	ID_AND_LENGTH(HOLE_DISCUS, 2),
	ID_AND_LENGTH(DISC, 0),
	ID_AND_LENGTH(WAVES, 3),
	ID_AND_LENGTH(SINE_WAVE, 2),
	//
	ID_AND_LENGTH(COSINE_WAVE, 2),
	ID_AND_LENGTH(SPIRAL_WAVE, 3),
	ID_AND_LENGTH(BELL, 2),
	ID_AND_LENGTH(BELL_POLAR, 3),
	//
	ID_AND_LENGTH(BELL_WAVE, 3),
	ID_AND_LENGTH(SOUCOUPOID, 0),
	ID_AND_LENGTH(ENNEPER_SURFACE_POLAR, 0),
	ID_AND_LENGTH(SINE_CONE, 2),
	//
	ID_AND_LENGTH(SPINNER, 0),
	ID_AND_LENGTH(FRESNEL, 3),
	ID_AND_LENGTH(TREFOIL_KNOTS2, 4),
	ID_AND_LENGTH(BOW_CURVE, 1),
	//
	ID_AND_LENGTH(TRIPLE_CORK_SCREW1, 4),
	ID_AND_LENGTH(TRIPLE_CORK_SCREW2, 6),
	ID_AND_LENGTH(TRIPLE_CORK_SCREW3, 4),
	ID_AND_LENGTH(BICORN_SURFACE, 0),
	//
	ID_AND_LENGTH(PIRIFORM_SURFACE, 3),
	ID_AND_LENGTH(KAPPA_SURFACE, 1),
	ID_AND_LENGTH(BULLET_NOSE, 2),
	ID_AND_LENGTH(SIEVERT_SURFACE, 1),
	//
	ID_AND_LENGTH(COSINE_SURFACE2, 0),
	ID_AND_LENGTH(CYLINDER, 1),
	ID_AND_LENGTH(EPIZYKLOID_CYLINDER, 4),
	ID_AND_LENGTH(HYPOZYKLOID_CYLINDER, 4),
	//
	ID_AND_LENGTH(LEMNISKATE_CYLINDER, 2),
	ID_AND_LENGTH(STROPHOIDE_CYLINDER, 2),
	ID_AND_LENGTH(ZISSOIDE_CYLINDER, 2),
	ID_AND_LENGTH(VERSIERA_AGNESI_CYLINDER, 2),
	//
	ID_AND_LENGTH(GAUSS_CYLINDER, 3),
};

float constants[] = {
	CONST_1(0),				 // PLANE
	CONST_3(1, 1, 1),		 // BOHEMIAN_DOME_SURFACE
	CONST_2(1, 0.2),		 // DINI_SURFACE
	CONST_3(1, 1, 1),		 // KLEIN_BOTTLE_SURFACE
	CONST_1(1),				 // MOEBIUS_BAND
	CONST_1(1.5),			 // CATENOID
	CONST_1(1.5),			 // HELICOID
	CONST_2(1.5, 0.5),		 // PARABOLOID
	CONST_1(0.5),			 // HYPERBOLIC_HELICOID
	CONST_2(1.5, 0.5),		 // HYPERBOLOID
	CONST_3(1.5, 0.5, 1),	 // WALLIS_CONICAL_SURFACE
	CONST_1(1.5),			 // SCHERK_SURFACE
	CONST_2(1.5, 0.5),		 // SCHERK_SURFACE
	CONST_1(1.5),			 // PILLOW_SHAPE
	CONST_3(1.5, 0.5, 1),	 // HORN
	CONST_3(1.5, 0.5, 1),	 // CRESENT
	CONST_2(1.5, 0.5),		 // TREFOIL_KNOTS
	CONST_4(1.5, 0.5, 1, 1), // DUPIN_CYCLIDE
	CONST_3(1.5, 0.5, 1),	 // GUIMARD_SURFACE
	CONST_1(1),				 // MENNS_SURFACE
	CONST_1(1),				 // MILK_BAG
	CONST_1(1.5),			 // ZINDLERS_CONOID
	CONST_1(1.5),			 // TRIPLE_POINT_TWIST
	CONST_2(1.5, 0.5),		 // TRASHCAN
	CONST_4(1.5, 0.5, 1, 1), // SPRING1
	CONST_3(1.5, 0.5, 1),	 // SPRING2
	CONST_1(1),				 // CONE
	CONST_3(1.5, 0.5, 1),	 // EGG
	CONST_3(1.5, 0.5, 1),	 // ISOLATOR
	CONST_1(1.5),			 // DROP_SURFACE
	CONST_1(1.5),			 // FACING_SNAIL
	CONST_2(1.5, 0.5),		 // PAPER_BAG
	CONST_3(1.5, 0.5, 1),	 // JEENER_KLEIN_SURFACE
	CONST_2(1.5, 0.5),		 // BONAN_JEENER_KLEIN_SURFACE
	CONST_3(1.5, 0.5, 1),	 // KLEIN_CYCLOID
	CONST_2(1.5, 0.5),		 // HOLE_DISCUS
	CONST_3(1.5, 0.5, 1),	 // WAVES
	CONST_2(1.5, 0.5),		 // SINE_WAVE
	CONST_2(1.5, 0.5),		 // COSINE_WAVE
	CONST_3(1.5, 0.5, 1),	 // SPIRAL_WAVE
	CONST_2(1.5, 0.5),		 // BELL
	CONST_2(1.5, 0.5),		 // BELL_POLAR
	CONST_3(1.5, 0.5, 1),	 // BELL_WAVE
	CONST_2(1.5, 0.5),		 // SINE_CONE
	CONST_3(1.5, 0.5, 1),	 // FRESNEL
	CONST_4(1.5, 0.5, 1, 1), // TREFOIL_KNOTS2
	CONST_1(1.5),			 // BOW_CURVE
	CONST_4(1.5, 0.5, 1, 1), // TRIPLE_CORK_SCREW1
	CONST_4(1.5, 0.5, 1, 1), // TRIPLE_CORK_SCREW2
	CONST_2(1, 1),			 // ...TRIPLE_CORK_SCREW2
	CONST_4(1.5, 0.5, 1, 1), // TRIPLE_CORK_SCREW3
	CONST_1(1.5),			 // KAPPA_SURFACE
	CONST_2(1.5, 0.5),		 // BULLET_NOSE
	CONST_1(1.5),			 // SIEVERT_SURFACE
	// Cylinder
	CONST_1(1),				 // CYLINDER
	CONST_4(1.5, 1, 0.5, 1), // EPIZYKLOID_CYLINDER
	CONST_4(1.5, 1, 0.5, 1), // HYPOZYKLOID_CYLINDER
	CONST_2(1, 1),			 // LEMNISKATE_CYLINDER
	CONST_2(1, 1),			 // STROPHOIDE_CYLINDER
	CONST_2(1, 1),			 // ZISSOIDE_CYLINDER
	CONST_2(1, 1),			 // VERSIERA_AGNESI_CYLINDER
	CONST_3(1, 1, 1),		 // GAUSS_CYLINDER
							 //Fruits
							 /*
	KIDNEY_SURFACE,
	PASULI_CAT_FRUIT_FIRST = KIDNEY_SURFACE,
	APPLE_SURFACE,
	APPLE2_SURFACE,
	LEMON_SURFACE,
	PASULI_CAT_FRUIT_LAST = LEMON_SURFACE
	// Shells & snails
	,
	CORNUCOPIA,
	PASULI_CAT_SHELL_FIRST = CORNUCOPIA,
	SNAIL,
	SEASHELL,
	SNAIL_SURFACE,
	SNAILS,
	PSEUDOHELICERAS_SUBCATENATUM,
	ASTROCERAS,
	BELLEROPHINA,
	EUHOPLITES,
	NAUTILUS,
	NATICA_STELLATA,
	MYA_ARENARIA,
	PASULI_CAT_SHELL_LAST = MYA_ARENARIA
	// Spheres
	,
	SPHERE,
	PASULI_CAT_SPHERE_FIRST = SPHERE,
	ELLIPSOID,
	SPHERE_V,
	SPHERE_UV,
	PSEUDOSPHERE,
	TWISTED_SPHERE,
	OPEN_SPHERE,
	WAVE_SPHERE,
	PASULI_CAT_SPHERE_LAST = WAVE_SPHERE
	// Spirals
	,
	ARCHIMEDIC_SPIRAL,
	PASULI_CAT_SPIRAL_FIRST = ARCHIMEDIC_SPIRAL,
	HYPERBOLIC_SPIRAL,
	FERMAT_SPIRAL,
	TANH_SPIRAL,
	LOG_SPIRAL,
	PASULI_CAT_SPIRAL_LAST = LOG_SPIRAL
	// Torus
	,
	TORUS,
	PASULI_CAT_TORUS_FIRST = TORUS,
	EIGHT_TORUS,
	ELLIPTIC_TORUS,
	SADDLE_TORUS,
	ANTISYMMETRIC_TORUS,
	TWISTED_EIGHT_TORUS,
	UMBILLIC_TORUS,
	WAVE_TORUS,
	BRAIDED_TORUS,
	LIMPET_TORUS,
	STRANGLED_TORUS,
	ASTROID_TORUS,
	TRICUSPOID_TORUS_1,
	TRICUSPOID_TORUS_2,
	NETHROID_TORUS_1,
	NETHROID_TORUS_2,
	LEMNISKATE_TORUS_1,
	LEMNISKATE_TORUS_2,
	EPIZYKLOID_TORUS_1,
	EPIZYKLOID_TORUS_2,
	HYPOZYKLOID_TORUS_1,
	HYPOZYKLOID_TORUS_2,
	PIRIFORM_TORUS_1,
	PIRIFORM_TORUS_2,
	BICORN_TORUS_1,
	BICORN_TORUS_2,
	CARDIOID_TORUS_1,
	CARDIOID_TORUS_2,
	CASSINIAN_OVAL_TORUS_1,
	CASSINIAN_OVAL_TORUS_2,
	GERONO_LEMNISKATE_TORUS_1,
	GERONO_LEMNISKATE_TORUS_2,
	CURLY_TORUS_1,
	CURLY_TORUS_2,
	SPIRAL_TORUS,
	TORUS_KNOT,
	GEAR_TORUS,
	PASULI_CAT_TORUS_LAST = GEAR_TORUS,
	NUMB_OF_SURFACES
	*/
};

#undef CONST_1
#undef CONST_2
#undef CONST_3

#undef PASULI_CONSTANT1_ENTRY
#undef PASULI_CONSTANT2_ENTRY
#undef PASULI_CONSTANT3_ENTRY

#include <stdio.h>

int findDefaultConstants(unsigned int id, double *pConstants, int size)
{
	unsigned int alreadyDefined =
		sizeof(id_and_length) / (2 * sizeof(char));

	printf("#defined = %d\n", alreadyDefined);

	if (id >= 255)
	{
		return 0;
	}
	/*
    for (size_t i = 0; i < numberOfPasuli; i++)
    {
        if (repositoryItems[i].id == id)
        {
            return repositoryItems[i].pFunc;
        }
    }
    */
	return 0;
}