#include <stdlib.h>
#include <stdio.h>
#include <string.h>
//
#include "pasuli_cfg.h"
#include "pasuli_repository.h"

#define PASULI_PARSUR_STATIC static
//#define PASULI_PARSUR_STATIC
//PASULI_PARSUR_STATIC

#define ID_AND_LENGTH(ID, L) \
	{                        \
		ID, L, 0             \
	}

#define ID_AND_LENGTH_C(ID, L, V) \
	{                             \
		ID, L, V                  \
	}

#define STD1_VALUES 120
#define DINI_VALUES 121
#define CYLINDER_VALUES 122
#define LEMON_VALUES 123
#define SPHERE_VALUES 124
#define TORUS1_VALUES 125
#define PLANAR_ENNEPER_VALUES 126

#define ALL_ONES 255
#define ALL_HALFES 254

// Constants defined so should be divided by 10 to get real (stored) value
#define CONSTANT_TUPLE_10(V1, V2, V3, V4, V5, V6) V1, V2, V3, V4, V5, V6

unsigned char constants_multiplied[] = {
	// STD1
	CONSTANT_TUPLE_10(15, 5, 10, 10, 10, 10),
	// DINI
	CONSTANT_TUPLE_10(10, 2, 0, 0, 0, 0),
	// CYLINDER
	CONSTANT_TUPLE_10(15, 10, 5, 10, 10, 10),
	// LEMON
	CONSTANT_TUPLE_10(20, 10, 0, 0, 0, 0),
	// Sphere
	CONSTANT_TUPLE_10(15, 10, 10, 0, 0, 0),
	// Torus 1
	CONSTANT_TUPLE_10(10, 10, 5, 10, 10, 10),
	// Planar Enneper Surface
	CONSTANT_TUPLE_10(20, 4, 10, 0, 0, 0),
};

#undef CONSTANT_TUPLE_10

unsigned char id_and_length[][3] = {
	ID_AND_LENGTH_C(PLANE, 1, 0),
	ID_AND_LENGTH_C(BOHEMIAN_DOME_SURFACE, 3, ALL_ONES),
	ID_AND_LENGTH(BOYS_SURFACE, 0),
	ID_AND_LENGTH(CROSS_CUP, 0),
	//
	ID_AND_LENGTH_C(DINI_SURFACE, 2, DINI_VALUES),
	ID_AND_LENGTH(ENNEPER_SURFACE, 0),
	ID_AND_LENGTH(HANDKERCHIEF, 0),
	ID_AND_LENGTH_C(KLEIN_BOTTLE_SURFACE, 3, ALL_ONES),
	//
	ID_AND_LENGTH_C(MOEBIUS_BAND, 1, ALL_ONES),
	ID_AND_LENGTH_C(MOEBIUS_BAND2, 3, ALL_ONES),
	ID_AND_LENGTH(MONKEY_SADDLE, 0),
	ID_AND_LENGTH(PLUECKER_CONOID, 0),
	ID_AND_LENGTH(ROMAN_SURFACE, 0),
	//
	ID_AND_LENGTH(SHOE_SURFACE, 0),
	ID_AND_LENGTH(SINE_SURFACE, 0),
	ID_AND_LENGTH(STEINBACH_SCREW, 0),
	ID_AND_LENGTH(WHITNEY_UMBRELLA, 0),
	//
	ID_AND_LENGTH_C(CATENOID, 1, STD1_VALUES),
	ID_AND_LENGTH_C(HELICOID, 1, STD1_VALUES),
	ID_AND_LENGTH_C(PARABOLOID, 2, STD1_VALUES),
	ID_AND_LENGTH_C(HYPERBOLIC_HELICOID, 1, ALL_HALFES),
	//
	ID_AND_LENGTH(FUNNEL, 0),
	ID_AND_LENGTH(TRACTROID, 0),
	ID_AND_LENGTH(CATALANS_SURFACE, 0),
	ID_AND_LENGTH_C(HYPERBOLOID, 2, STD1_VALUES),
	//
	ID_AND_LENGTH(HENNEBERGS_SURFACE, 0),
	ID_AND_LENGTH(SWALLOW_SURFACE, 0),
	ID_AND_LENGTH_C(WALLIS_CONICAL_SURFACE, 3, STD1_VALUES),
	ID_AND_LENGTH(MAEDERS_OWL, 0),
	//
	ID_AND_LENGTH(RICHMOND_SURFACE, 0),
	ID_AND_LENGTH_C(SCHERK_SURFACE, 1, STD1_VALUES),
	ID_AND_LENGTH(COSINE_SURFACE, 0),
	ID_AND_LENGTH(EIGHT_SURFACE, 0),
	//
	ID_AND_LENGTH(JET_SURFACE, 0),
	ID_AND_LENGTH_C(DROP, 2, STD1_VALUES),
	ID_AND_LENGTH(TRIAXIAL_TEARDROP, 0),
	ID_AND_LENGTH_C(PILLOW_SHAPE, 1, STD1_VALUES),
	//
	ID_AND_LENGTH(FISH_SURFACE, 0),
	ID_AND_LENGTH_C(HORN, 3, STD1_VALUES),
	ID_AND_LENGTH(BENT_HORNS, 0),
	ID_AND_LENGTH(HYPERBOLIC_OCTAHEDRON, 0),
	//
	ID_AND_LENGTH(PSEUDO_CROSS_CAP, 0),
	ID_AND_LENGTH_C(CRESENT, 3, STD1_VALUES),
	ID_AND_LENGTH(STILETTO_SURFACE, 0),
	ID_AND_LENGTH(KUENS_SURFACE, 0),
	//
	ID_AND_LENGTH_C(TREFOIL_KNOTS, 2, STD1_VALUES),
	ID_AND_LENGTH(TRANGULOID_TREFOIL, 0),
	ID_AND_LENGTH(CROWN, 0),
	ID_AND_LENGTH(TWISTED_PIPE_SURFACE, 0),
	//
	ID_AND_LENGTH(LOOP, 0),
	ID_AND_LENGTH_C(DUPIN_CYCLIDE, 4, STD1_VALUES),
	ID_AND_LENGTH_C(GUIMARD_SURFACE, 3, STD1_VALUES),
	ID_AND_LENGTH_C(MENNS_SURFACE, 1, ALL_ONES),
	//
	ID_AND_LENGTH_C(MILK_BAG, 1, ALL_ONES),
	ID_AND_LENGTH(TRIAXIAL_TRITORUS, 0),
	ID_AND_LENGTH(VERRILL_SURFACE, 0),
	ID_AND_LENGTH(ZINDLERS_CONOID, 1),
	//
	ID_AND_LENGTH(FOLIUM, 0),
	ID_AND_LENGTH(LEMNISCAPE, 0),
	ID_AND_LENGTH(TRIPLE_POINT_TWIST, 1),
	ID_AND_LENGTH(TRASHCAN, 2),
	//
	ID_AND_LENGTH(SPRING1, 4),
	ID_AND_LENGTH(SPRING2, 3),
	ID_AND_LENGTH_C(CONE, 1, ALL_ONES),
	ID_AND_LENGTH(EGG, 3),
	//
	ID_AND_LENGTH_C(ISOLATOR, 3, STD1_VALUES),
	ID_AND_LENGTH(HYPERBOLIC_PARABOLOID, 0),
	ID_AND_LENGTH_C(FACING_SNAIL, 1, STD1_VALUES),
	ID_AND_LENGTH_C(PAPER_BAG, 2, STD1_VALUES),
	//
	ID_AND_LENGTH_C(JEENER_KLEIN_SURFACE, 3, STD1_VALUES),
	ID_AND_LENGTH_C(BONAN_JEENER_KLEIN_SURFACE, 2, STD1_VALUES),
	ID_AND_LENGTH_C(KLEIN_CYCLOID, 3, STD1_VALUES),
	ID_AND_LENGTH(DOUBLE_CONE, 0),
	//
	ID_AND_LENGTH(HOLE_DISC, 0),
	ID_AND_LENGTH(PISOT_TRIAXIAL, 0),
	ID_AND_LENGTH(TRIAXIAL_HEXATORUS, 0),
	ID_AND_LENGTH(TWISTED_HEART, 0),
	//
	ID_AND_LENGTH_C(HOLE_DISCUS, 2, STD1_VALUES),
	ID_AND_LENGTH(DISC, 0),
	ID_AND_LENGTH_C(WAVES, 3, STD1_VALUES),
	ID_AND_LENGTH_C(SINE_WAVE, 2, STD1_VALUES),
	//
	ID_AND_LENGTH_C(DROP_SURFACE, 1, STD1_VALUES),
	ID_AND_LENGTH_C(ASTROIDAL_ELLIPSOID, 3, ALL_ONES),
	ID_AND_LENGTH_C(COSINE_WAVE, 2, STD1_VALUES),
	ID_AND_LENGTH_C(SPIRAL_WAVE, 3, STD1_VALUES),
	ID_AND_LENGTH_C(BELL, 2, STD1_VALUES),
	ID_AND_LENGTH_C(BELL_POLAR, 3, STD1_VALUES),
	//
	ID_AND_LENGTH_C(BELL_WAVE, 3, STD1_VALUES),
	ID_AND_LENGTH(SOUCOUPOID, 0),
	ID_AND_LENGTH(ENNEPER_SURFACE_POLAR, 0),
	ID_AND_LENGTH_C(SINE_CONE, 2, STD1_VALUES),
	//
	ID_AND_LENGTH(SPINNER, 0),
	ID_AND_LENGTH_C(FRESNEL, 3, STD1_VALUES),
	ID_AND_LENGTH_C(TREFOIL_KNOTS2, 4, STD1_VALUES),
	ID_AND_LENGTH_C(BOW_CURVE, 1, STD1_VALUES),
	//
	ID_AND_LENGTH_C(TRIPLE_CORK_SCREW1, 4, STD1_VALUES),
	ID_AND_LENGTH_C(TRIPLE_CORK_SCREW2, 6, STD1_VALUES),
	ID_AND_LENGTH_C(TRIPLE_CORK_SCREW3, 4, STD1_VALUES),
	ID_AND_LENGTH(BICORN_SURFACE, 0),
	//
	ID_AND_LENGTH_C(PIRIFORM_SURFACE, 3, STD1_VALUES),
	ID_AND_LENGTH_C(KAPPA_SURFACE, 1, STD1_VALUES),
	ID_AND_LENGTH_C(BULLET_NOSE, 2, STD1_VALUES),
	ID_AND_LENGTH_C(SIEVERT_SURFACE, 1, STD1_VALUES),
	//
	ID_AND_LENGTH(COSINE_SURFACE2, 0),
	ID_AND_LENGTH_C(CYLINDER, 1, ALL_ONES),
	ID_AND_LENGTH_C(EPIZYKLOID_CYLINDER, 4, CYLINDER_VALUES),
	ID_AND_LENGTH_C(HYPOZYKLOID_CYLINDER, 4, CYLINDER_VALUES),
	//
	ID_AND_LENGTH_C(LEMNISKATE_CYLINDER, 2, ALL_ONES),
	ID_AND_LENGTH_C(STROPHOIDE_CYLINDER, 2, ALL_ONES),
	ID_AND_LENGTH_C(ZISSOIDE_CYLINDER, 2, ALL_ONES),
	ID_AND_LENGTH_C(VERSIERA_AGNESI_CYLINDER, 2, ALL_ONES),
	//
	ID_AND_LENGTH_C(GAUSS_CYLINDER, 3, ALL_ONES),
	//Fruits
	ID_AND_LENGTH(KIDNEY_SURFACE, 0),
	ID_AND_LENGTH(APPLE_SURFACE, 0),
	ID_AND_LENGTH_C(APPLE2_SURFACE, 2, STD1_VALUES),
	//
	ID_AND_LENGTH_C(LEMON_SURFACE, 2, LEMON_VALUES),
	// Shells & snails
	ID_AND_LENGTH_C(CORNUCOPIA, 2, STD1_VALUES), // TODO
	ID_AND_LENGTH_C(SNAIL, 2, STD1_VALUES),		 // TODO
	ID_AND_LENGTH_C(SEASHELL, 4, STD1_VALUES),	 // TODO
	//
	ID_AND_LENGTH(SNAIL_SURFACE, 0),
	ID_AND_LENGTH_C(SNAILS, 7, STD1_VALUES),		// TODO
	ID_AND_LENGTH(PSEUDOHELICERAS_SUBCATENATUM, 0), // TODO R
	ID_AND_LENGTH(ASTROCERAS, 0),					// TODO R
	//
	ID_AND_LENGTH(BELLEROPHINA, 0),	   // TODO R
	ID_AND_LENGTH(EUHOPLITES, 0),	   // TODO R
	ID_AND_LENGTH(NAUTILUS, 0),		   // TODO R
	ID_AND_LENGTH(NATICA_STELLATA, 0), // TODO R
	//
	ID_AND_LENGTH(MYA_ARENARIA, 0), // TODO R
	// Sphere
	ID_AND_LENGTH(SPHERE, 0),
	ID_AND_LENGTH_C(ELLIPSOID, 3, SPHERE_VALUES),
	ID_AND_LENGTH(SPHERE_V, 0),
	//
	ID_AND_LENGTH(SPHERE_UV, 0),
	ID_AND_LENGTH(PSEUDOSPHERE, 0),
	ID_AND_LENGTH_C(TWISTED_SPHERE, 2, ALL_ONES),
	ID_AND_LENGTH(OPEN_SPHERE, 0),
	//
	ID_AND_LENGTH(WAVE_SPHERE, 0),
	// Spirals
	ID_AND_LENGTH_C(ARCHIMEDIC_SPIRAL, 1, ALL_ONES),
	ID_AND_LENGTH_C(HYPERBOLIC_SPIRAL, 1, ALL_ONES),
	ID_AND_LENGTH_C(FERMAT_SPIRAL, 1, ALL_ONES),
	//
	ID_AND_LENGTH_C(TANH_SPIRAL, 2, ALL_ONES),
	ID_AND_LENGTH_C(LOG_SPIRAL, 2, ALL_ONES),
	// Torus
	ID_AND_LENGTH_C(TORUS, 2, STD1_VALUES),
	ID_AND_LENGTH_C(EIGHT_TORUS, 1, ALL_ONES),
	//
	ID_AND_LENGTH_C(ELLIPTIC_TORUS, 1, ALL_ONES),
	ID_AND_LENGTH(SADDLE_TORUS, 0),
	ID_AND_LENGTH_C(ANTISYMMETRIC_TORUS, 3, STD1_VALUES),
	ID_AND_LENGTH_C(TWISTED_EIGHT_TORUS, 2, STD1_VALUES),
	//
	ID_AND_LENGTH_C(UMBILLIC_TORUS, 2, STD1_VALUES),
	ID_AND_LENGTH_C(WAVE_TORUS, 4, STD1_VALUES),
	ID_AND_LENGTH_C(BRAIDED_TORUS, 4, ALL_ONES),
	ID_AND_LENGTH(LIMPET_TORUS, 0),
	//
	ID_AND_LENGTH_C(STRANGLED_TORUS, 3, ALL_ONES),
	ID_AND_LENGTH_C(ASTROID_TORUS, 2, ALL_ONES),
	ID_AND_LENGTH_C(TRICUSPOID_TORUS_1, 2, STD1_VALUES),
	ID_AND_LENGTH_C(TRICUSPOID_TORUS_2, 2, STD1_VALUES),
	//
	ID_AND_LENGTH_C(NEPHROID_TORUS_1, 2, STD1_VALUES),
	ID_AND_LENGTH_C(NEPHROID_TORUS_2, 2, STD1_VALUES),
	ID_AND_LENGTH_C(LEMNISKATE_TORUS_1, 2, STD1_VALUES),
	ID_AND_LENGTH_C(LEMNISKATE_TORUS_2, 2, STD1_VALUES),
	//
	ID_AND_LENGTH_C(EPIZYKLOID_TORUS_1, 4, TORUS1_VALUES),
	ID_AND_LENGTH_C(EPIZYKLOID_TORUS_2, 4, TORUS1_VALUES),
	ID_AND_LENGTH_C(HYPOZYKLOID_TORUS_1, 4, TORUS1_VALUES),
	ID_AND_LENGTH_C(HYPOZYKLOID_TORUS_2, 4, TORUS1_VALUES),
	//
	ID_AND_LENGTH_C(PIRIFORM_TORUS_1, 2, ALL_ONES),
	ID_AND_LENGTH_C(PIRIFORM_TORUS_2, 2, ALL_ONES),
	ID_AND_LENGTH_C(BICORN_TORUS_1, 2, ALL_ONES),
	ID_AND_LENGTH_C(BICORN_TORUS_2, 2, ALL_ONES),
	//
	ID_AND_LENGTH_C(CARDIOID_TORUS_1, 2, ALL_ONES),
	ID_AND_LENGTH_C(CARDIOID_TORUS_2, 2, ALL_ONES),
	ID_AND_LENGTH_C(CASSINIAN_OVAL_TORUS_1, 3, ALL_ONES),
	ID_AND_LENGTH_C(CASSINIAN_OVAL_TORUS_2, 3, ALL_ONES),
	//
	ID_AND_LENGTH_C(GERONO_LEMNISKATE_TORUS_1, 2, ALL_ONES),
	ID_AND_LENGTH_C(GERONO_LEMNISKATE_TORUS_2, 2, ALL_ONES),
	ID_AND_LENGTH_C(CURLY_TORUS_1, 4, ALL_ONES),
	ID_AND_LENGTH_C(CURLY_TORUS_2, 4, ALL_ONES),
	//
	ID_AND_LENGTH_C(SPIRAL_TORUS, 4, ALL_ONES),
	ID_AND_LENGTH_C(TORUS_KNOT, 5, ALL_ONES),
	ID_AND_LENGTH_C(GEAR_TORUS, 4, ALL_ONES),
	// END
	// NEW ONES after Feb 22, 2021
	ID_AND_LENGTH(PEANO_SURFACE, 0),
	ID_AND_LENGTH_C(PEANO_SURFACE2, 4, ALL_ONES),
	ID_AND_LENGTH_C(VASE_HEAD, 2, ALL_ONES),
	ID_AND_LENGTH(PLUECKER_CONOID2, 0),
	ID_AND_LENGTH_C(MONKEY_SADDLE2, 1, ALL_ONES),
	ID_AND_LENGTH(BOYS_SURFACE2, 0),
	ID_AND_LENGTH_C(SKIDAN_RULED_SURFACE, 3, ALL_ONES),
	ID_AND_LENGTH(SCHERK_SURFACE2, 0),
	ID_AND_LENGTH_C(CATALANS_SURFACE2, 1, ALL_ONES),
	ID_AND_LENGTH(WRINKLE_SPHERE, 0),
	ID_AND_LENGTH_C(WRINKLE_SPHERE2, 1, 20),
	ID_AND_LENGTH_C(SNAIL2, 1, ALL_ONES),
	ID_AND_LENGTH(KLEIN_BOTTLE_SURFACE2, 0),
	ID_AND_LENGTH(FOUR_INTERSECTING_DISCS, 0),
	ID_AND_LENGTH_C(KAI_WING_FUNG_SURFACE1, 1, ALL_ONES),
	ID_AND_LENGTH(KAI_WING_FUNG_SURFACE2, 0),
	ID_AND_LENGTH(RICHMOND_SURFACE2, 0),
	ID_AND_LENGTH_C(RICHMOND_SURFACE3, 1, 2),
	ID_AND_LENGTH(ENNEPER_SURFACE2, 0),
	ID_AND_LENGTH(ENNEPER_SURFACE3, 0),
	ID_AND_LENGTH_C(WAVY_ENNEPER_SURFACE, 1, 2),
	ID_AND_LENGTH(TWISTED_RIBBON, 0),
	ID_AND_LENGTH_C(PLANAR_ENNEPER_SURFACE, 3, PLANAR_ENNEPER_VALUES),
	ID_AND_LENGTH(CAYLEY_SURFACE, 0),
	ID_AND_LENGTH(ROMAN_SURFACE2, 0),
	ID_AND_LENGTH(MOEBIUS_BAND3, 0),
	ID_AND_LENGTH_C(VIRICH_CYCLIC_SURFACE, 4, ALL_ONES),
	ID_AND_LENGTH_C(PSEUDODEVELOPABLE_HELICOID, 2, ALL_ONES),
	ID_AND_LENGTH(CROSS_CUP2, 0),
	ID_AND_LENGTH_C(CROSS_CUP3, 1, ALL_ONES),
	ID_AND_LENGTH(CUSPIDAL_BUTTERFLY, 0),
	ID_AND_LENGTH(CUSPIDAL_LIPS, 0),
	ID_AND_LENGTH(CUSPIDAL_EDGE, 0),
	ID_AND_LENGTH(CUSPIDAL_BEAKS, 0),
	ID_AND_LENGTH(DING_DONG_SURFACE, 0),
	ID_AND_LENGTH(TOOTH_SURFACE, 0),
	ID_AND_LENGTH(LAWSON_BOTTLE, 0),
	ID_AND_LENGTH(GOBLET, 0),
	ID_AND_LENGTH(BOWTIE, 0),
	ID_AND_LENGTH_C(HORNLET_SURFACE, 4, ALL_ONES),
	ID_AND_LENGTH_C(BALLS_CYLINDROID, 1, ALL_ONES),
	ID_AND_LENGTH_C(EPITROCHOIDAL_SURFACE, 2, ALL_ONES),
	ID_AND_LENGTH_C(MORIN_SURFACE, 2, ALL_ONES),
	ID_AND_LENGTH_C(CROSSED_TROUGH_SURFACE, 1, ALL_ONES),
	ID_AND_LENGTH_C(HECTOR_GUINARDS_SURFACE, 3, ALL_ONES),
	ID_AND_LENGTH_C(AGNESI_CURL, 2, ALL_ONES),
	ID_AND_LENGTH(SPINNING_TOP1, 0),
	ID_AND_LENGTH(SPINNING_TOP2, 0),
	ID_AND_LENGTH(KISS_SURFACE, 0),
	ID_AND_LENGTH(NEOVIUS_SURFACE, 0),
	ID_AND_LENGTH_C(RULED_ROTOR_CYLINDROID, 3, ALL_ONES),
	ID_AND_LENGTH_C(PARABOLIC_HUMMING_TOP, 2, ALL_ONES),
	ID_AND_LENGTH(SINE_CUBE, 0),
	ID_AND_LENGTH(WREATH, 0),
	ID_AND_LENGTH_C(EGG_SURFACE, 2, STD1_VALUES),
	ID_AND_LENGTH(BOURS_MINIMAL_SURFACE, 0),
	ID_AND_LENGTH_C(UMBRELLA_SURFACE, 4, ALL_ONES),
};

void testDefaultConstants()
{
	size_t numberOf = 256;

	unsigned char *pStates = malloc(numberOf);

	memset(pStates, 0, numberOf);

	unsigned int alreadyDefined =
		sizeof(id_and_length) / (3 * sizeof(char));

	printf("#defined = %d\n", alreadyDefined);

	for (int idx = 0; idx < alreadyDefined; idx++)
	{
		int id = id_and_length[idx][0];

		if (((id <= 0) || (id > 255)))
		{
			printf("Invalid surface at index %d, value %d", idx, id);
			continue;
		}
		if (pStates[id] > 0)
		{
			printf("Constants already defined for surface %d", id);
		}
		pStates[id] += 1;
	}

	for (int idx = 1; idx < NUMB_OF_SURFACES; idx++)
	{
		if (pStates[idx] == 0)
		{
			printf("Constants not yet defined for surface %d\n", idx);
		}
	}

	free(pStates);
}

int findDefaultConstants(unsigned int id, double *pConstants, int size)
{
	unsigned int alreadyDefined =
		sizeof(id_and_length) / (3 * sizeof(char));

	if (id >= 255)
	{
		// Not found
		return -1;
	}

	for (size_t idx = 0; idx < alreadyDefined; idx++)
	{
		int idInArray = id_and_length[idx][0];
		if (id == idInArray)
		{
			int length = id_and_length[idx][1];
			if (length > 0)
			{
				if (length < size)
				{
					// Not enough space to store
					return -2;
				}
				int typeOrValue = id_and_length[idx][2];

				if (typeOrValue == ALL_ONES || typeOrValue == ALL_HALFES)
				{
					double v = typeOrValue == ALL_ONES ? 1.0 : 0.5;

					for (int j = 0; j < length; j++)
					{
						pConstants[j] = v;
					}
				}

				if (typeOrValue >= STD1_VALUES && typeOrValue <= TORUS1_VALUES)
				{
					int idx = (typeOrValue - STD1_VALUES) * 6;

					if (idx > sizeof(constants_multiplied) / sizeof(char) ||
						length > 6)
					{
						// INTERNAL error
						return -3;
					}

					for (int j = 0; j < length; j++)
					{
						pConstants[j] = (constants_multiplied[j] * 1.0) / 10.0;
					}
				}
				else
				{
					for (int j = 0; j < length; j++)
					{
						pConstants[j] = typeOrValue * 1.0;
					}
				}
			}
			return length;
		}
	}

	// Not found
	return -1;
}

#undef STD1_VALUES
#undef DINI_VALUES
#undef CYLINDER_VALUES
#undef LEMON_VALUES
#undef SPHERE_VALUES
#undef TORUS1_VALUES

#define PASULI_IMPLEMENTED(ID, IMPL_MASK) \
	{                                     \
		ID, IMPL_MASK                     \
	}

#define IMPL_POS 0x1
#define IMPL_UD 0x2
#define IMPL_VD 0x4
#define IMPL_N 0x8
#define IMPL_UUD 0x10
#define IMPL_UVD 0x20
#define IMPL_VVD 0x40
#define IMPL_ALL 0x7F
#define IMPL_ONLY_POS_UD_VD (IMPL_POS | IMPL_UD | IMPL_VD)
#define IMPL_NORMAL_BY_CROSS_PRODUCT 0x80
#define IMPL_NO_BEGIN_NORMAL IMPL_ONLY_POS_UD_VD | IMPL_NORMAL_BY_CROSS_PRODUCT

#define IMPL_NO_2DERIV 0x0F

#define IMPL_MINUS(ALL_VAL, TO_SUBTRACT) (ALL_VAL - (TO_SUBTRACT))

unsigned char implementationStates[][2] = {
	// Cylinder
	PASULI_IMPLEMENTED(CYLINDER, IMPL_ALL),
	PASULI_IMPLEMENTED(EPIZYKLOID_CYLINDER, IMPL_ALL),
	PASULI_IMPLEMENTED(GAUSS_CYLINDER, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(HYPOZYKLOID_CYLINDER, IMPL_ALL),
	PASULI_IMPLEMENTED(LEMNISKATE_CYLINDER, IMPL_MINUS(IMPL_ALL, IMPL_UUD)),
	PASULI_IMPLEMENTED(STROPHOIDE_CYLINDER, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(VERSIERA_AGNESI_CYLINDER, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(ZISSOIDE_CYLINDER, IMPL_NO_BEGIN_NORMAL),
	// Fruits
	PASULI_IMPLEMENTED(APPLE_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(APPLE2_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(KIDNEY_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(LEMON_SURFACE, IMPL_ALL),
	// Shells
	PASULI_IMPLEMENTED(CORNUCOPIA, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SEASHELL, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(SNAIL_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(SNAIL, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(SNAILS, IMPL_NO_BEGIN_NORMAL),
	//Following Snails are special 'instances' of Snails
	PASULI_IMPLEMENTED(ASTROCERAS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(BELLEROPHINA, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(EUHOPLITES, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(MYA_ARENARIA, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(NATICA_STELLATA, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(NAUTILUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(PSEUDOHELICERAS_SUBCATENATUM, IMPL_NO_BEGIN_NORMAL),
	// Spheres
	PASULI_IMPLEMENTED(ELLIPSOID, IMPL_ALL),
	PASULI_IMPLEMENTED(OPEN_SPHERE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(PSEUDOSPHERE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SPHERE_UV, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SPHERE_V, IMPL_ALL),
	PASULI_IMPLEMENTED(SPHERE, IMPL_ALL),
	PASULI_IMPLEMENTED(TWISTED_SPHERE, IMPL_ALL),
	PASULI_IMPLEMENTED(WAVE_SPHERE, IMPL_ALL),
	// Spirals
	PASULI_IMPLEMENTED(ARCHIMEDIC_SPIRAL, IMPL_ALL),
	PASULI_IMPLEMENTED(FERMAT_SPIRAL, IMPL_ALL),
	PASULI_IMPLEMENTED(HYPERBOLIC_SPIRAL, IMPL_ALL),
	PASULI_IMPLEMENTED(LOG_SPIRAL, IMPL_ALL),
	PASULI_IMPLEMENTED(TANH_SPIRAL, IMPL_NO_2DERIV),
	// Surfaces
	PASULI_IMPLEMENTED(BELL_POLAR, IMPL_ALL),
	PASULI_IMPLEMENTED(BELL_WAVE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(BELL, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(BENT_HORNS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(BICORN_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(BOHEMIAN_DOME_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(BONAN_JEENER_KLEIN_SURFACE, IMPL_POS),
	//
	PASULI_IMPLEMENTED(BOW_CURVE, IMPL_ALL),
	PASULI_IMPLEMENTED(BOYS_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(BULLET_NOSE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(CATALANS_SURFACE, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(CATENOID, IMPL_ALL),
	PASULI_IMPLEMENTED(CONE, IMPL_ALL),
	PASULI_IMPLEMENTED(COSINE_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(COSINE_SURFACE2, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(COSINE_WAVE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(CRESENT, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CROSS_CUP, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CROWN, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(DINI_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(DISC, IMPL_ALL),
	PASULI_IMPLEMENTED(DOUBLE_CONE, IMPL_ALL),
	PASULI_IMPLEMENTED(DROP_SURFACE, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(DROP, IMPL_ALL),
	PASULI_IMPLEMENTED(DUPIN_CYCLIDE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(EGG, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(EIGHT_SURFACE, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(ENNEPER_SURFACE_POLAR, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(ENNEPER_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(FACING_SNAIL, IMPL_ALL),
	PASULI_IMPLEMENTED(FISH_SURFACE, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(FOLIUM, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(FRESNEL, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(FUNNEL, IMPL_ALL),
	PASULI_IMPLEMENTED(GUIMARD_SURFACE, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(HANDKERCHIEF, IMPL_ALL),
	PASULI_IMPLEMENTED(HELICOID, IMPL_ALL),
	PASULI_IMPLEMENTED(HENNEBERGS_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(HOLE_DISC, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(HOLE_DISCUS, IMPL_ALL),
	PASULI_IMPLEMENTED(HORN, IMPL_ALL),
	PASULI_IMPLEMENTED(HYPERBOLIC_HELICOID, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(HYPERBOLIC_OCTAHEDRON, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(HYPERBOLIC_PARABOLOID, IMPL_ALL),
	PASULI_IMPLEMENTED(HYPERBOLOID, IMPL_ALL),
	PASULI_IMPLEMENTED(ISOLATOR, IMPL_ALL),
	PASULI_IMPLEMENTED(JEENER_KLEIN_SURFACE, IMPL_POS),
	//
	PASULI_IMPLEMENTED(JET_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(KAPPA_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(KLEIN_BOTTLE_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(KLEIN_CYCLOID, IMPL_POS),
	//
	PASULI_IMPLEMENTED(KUENS_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(LEMNISCAPE, IMPL_POS),
	PASULI_IMPLEMENTED(LOOP, IMPL_ALL),
	PASULI_IMPLEMENTED(MAEDERS_OWL, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(MENNS_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(MILK_BAG, IMPL_ALL),
	PASULI_IMPLEMENTED(MOEBIUS_BAND, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(MOEBIUS_BAND2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(MONKEY_SADDLE, IMPL_ALL),
	PASULI_IMPLEMENTED(PAPER_BAG, IMPL_ALL),
	PASULI_IMPLEMENTED(PARABOLOID, IMPL_ALL),
	PASULI_IMPLEMENTED(PILLOW_SHAPE, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(PLANE, IMPL_ALL),
	PASULI_IMPLEMENTED(PIRIFORM_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(PISOT_TRIAXIAL, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(PLUECKER_CONOID, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(PSEUDO_CROSS_CAP, IMPL_ALL),
	PASULI_IMPLEMENTED(RICHMOND_SURFACE, IMPL_NO_BEGIN_NORMAL), //Check again ?
	PASULI_IMPLEMENTED(ROMAN_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SCHERK_SURFACE, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(SHOE_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(SIEVERT_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(SINE_CONE, IMPL_ALL),
	PASULI_IMPLEMENTED(SINE_SURFACE, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(SINE_WAVE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SOUCOUPOID, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SPINNER, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(SPIRAL_WAVE, IMPL_NO_2DERIV),
	//
	PASULI_IMPLEMENTED(SPRING1, IMPL_ALL),
	PASULI_IMPLEMENTED(SPRING2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(STEINBACH_SCREW, IMPL_ALL),
	PASULI_IMPLEMENTED(STILETTO_SURFACE, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(SWALLOW_SURFACE, IMPL_ALL),
	PASULI_IMPLEMENTED(TRACTROID, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(TRANGULOID_TREFOIL, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TRASHCAN, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(TREFOIL_KNOTS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TREFOIL_KNOTS2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TRIAXIAL_HEXATORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TRIAXIAL_TEARDROP, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(TRIAXIAL_TRITORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TRIPLE_CORK_SCREW1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TRIPLE_CORK_SCREW2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TRIPLE_CORK_SCREW3, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(TRIPLE_POINT_TWIST, IMPL_ALL),
	PASULI_IMPLEMENTED(TWISTED_HEART, IMPL_POS),
	PASULI_IMPLEMENTED(TWISTED_PIPE_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(VERRILL_SURFACE, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(WALLIS_CONICAL_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(WAVES, IMPL_ALL),
	PASULI_IMPLEMENTED(WHITNEY_UMBRELLA, IMPL_ALL),
	PASULI_IMPLEMENTED(ZINDLERS_CONOID, IMPL_NO_2DERIV),
	// Torus surfaces
	PASULI_IMPLEMENTED(ANTISYMMETRIC_TORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(ASTROID_TORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(BICORN_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(BICORN_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(BRAIDED_TORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CARDIOID_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CARDIOID_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CASSINIAN_OVAL_TORUS_1, IMPL_POS),
	//
	PASULI_IMPLEMENTED(CASSINIAN_OVAL_TORUS_2, IMPL_POS),
	PASULI_IMPLEMENTED(CURLY_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CURLY_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(EIGHT_TORUS, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(ELLIPTIC_TORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(EPIZYKLOID_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(EPIZYKLOID_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(GEAR_TORUS, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(GERONO_LEMNISKATE_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(GERONO_LEMNISKATE_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(HYPOZYKLOID_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(HYPOZYKLOID_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(LEMNISKATE_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(LEMNISKATE_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(LIMPET_TORUS, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(NEPHROID_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(NEPHROID_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(PIRIFORM_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(PIRIFORM_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(SADDLE_TORUS, IMPL_POS),
	//
	PASULI_IMPLEMENTED(SPIRAL_TORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(STRANGLED_TORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TORUS_KNOT, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TORUS, IMPL_ALL),
	//
	PASULI_IMPLEMENTED(TRICUSPOID_TORUS_1, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TRICUSPOID_TORUS_2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TWISTED_EIGHT_TORUS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(UMBILLIC_TORUS, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(WAVE_TORUS, IMPL_NO_BEGIN_NORMAL),
	//
	// New ones
	//
	PASULI_IMPLEMENTED(AGNESI_CURL, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(ASTROIDAL_ELLIPSOID, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(BALLS_CYLINDROID, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(BOWTIE, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(BOYS_SURFACE2, IMPL_POS),
	PASULI_IMPLEMENTED(CATALANS_SURFACE2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CAYLEY_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(CROSS_CUP2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(CROSS_CUP3, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CROSSED_TROUGH_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(CUSPIDAL_BEAKS, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(CUSPIDAL_BUTTERFLY, IMPL_NO_2DERIV),
	//
	PASULI_IMPLEMENTED(CUSPIDAL_EDGE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(CUSPIDAL_LIPS, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(DING_DONG_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(ENNEPER_SURFACE2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(ENNEPER_SURFACE3, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(EPITROCHOIDAL_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(FOUR_INTERSECTING_DISCS, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(GOBLET, IMPL_NO_2DERIV),
	//
	PASULI_IMPLEMENTED(HECTOR_GUINARDS_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(HORNLET_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(KAI_WING_FUNG_SURFACE1, IMPL_POS),
	PASULI_IMPLEMENTED(KAI_WING_FUNG_SURFACE2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(KISS_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(KLEIN_BOTTLE_SURFACE2, IMPL_POS),
	PASULI_IMPLEMENTED(LAWSON_BOTTLE, IMPL_POS),
	PASULI_IMPLEMENTED(MOEBIUS_BAND3, IMPL_POS),
	//
	PASULI_IMPLEMENTED(MONKEY_SADDLE2, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(MORIN_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(NEOVIUS_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(PARABOLIC_HUMMING_TOP, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(PEANO_SURFACE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(PEANO_SURFACE2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(PLANAR_ENNEPER_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(PLUECKER_CONOID2, IMPL_NO_2DERIV),
	//
	PASULI_IMPLEMENTED(PSEUDODEVELOPABLE_HELICOID, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(RICHMOND_SURFACE2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(RICHMOND_SURFACE3, IMPL_POS),
	PASULI_IMPLEMENTED(ROMAN_SURFACE2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(RULED_ROTOR_CYLINDROID, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SCHERK_SURFACE2, IMPL_POS),
	PASULI_IMPLEMENTED(SKIDAN_RULED_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(SNAIL2, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(SPINNING_TOP1, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(SPINNING_TOP2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(TOOTH_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(TWISTED_RIBBON, IMPL_NO_2DERIV),
	//
	PASULI_IMPLEMENTED(VASE_HEAD, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(VIRICH_CYCLIC_SURFACE, IMPL_POS),
	PASULI_IMPLEMENTED(WAVY_ENNEPER_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(WRINKLE_SPHERE, IMPL_NO_BEGIN_NORMAL),
	//
	PASULI_IMPLEMENTED(WRINKLE_SPHERE2, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(SINE_CUBE, IMPL_NO_2DERIV),
	PASULI_IMPLEMENTED(WREATH, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(EGG_SURFACE, IMPL_POS),
	//
	PASULI_IMPLEMENTED(BOURS_MINIMAL_SURFACE, IMPL_NO_BEGIN_NORMAL),
	PASULI_IMPLEMENTED(UMBRELLA_SURFACE, IMPL_NO_BEGIN_NORMAL),
};

#undef PASULI_IMPLEMENTED

unsigned char getImplementationState(unsigned int id)
{
	unsigned int alreadyImplemented =
		sizeof(implementationStates) / (2 * sizeof(char));

	printf("#implemented/checked = %d\n", alreadyImplemented);

	if ((id <= 0) || (id > NUMB_OF_SURFACES))
	{
		return 0;
	}

	for (int i = 0; i < alreadyImplemented; i++)
	{
		if (implementationStates[i][0] == id)
		{
			return implementationStates[i][1];
		}
	}

	return 0;
}

typedef struct _pasuli_name_type
{
	char *szName;
	int _ID;
} pasuli_name_type;

#define PASULI_STORE_NAME 1
#define PASULI_STORE_DESC 1

typedef struct
{
	/**
	 * Surfaces ID
	 */
	unsigned char ID;
#if (PASULI_STORE_NAME != 0)
	char *pszName;
#endif
	/**
	 * Pointer to text description
	 */
#if (PASULI_STORE_DESC != 0)
	char **pszDesc;
#endif
} PaSuLiTextDescType;

#if ((PASULI_STORE_NAME != 0) && (PASULI_STORE_DESC != 0))

#define PASULI_SET_DESC(NAME, _ID, PTR) \
	{                                   \
		_ID, NAME, &PTR                 \
	}

#endif

PaSuLiTextDescType parsur_desc_array[] = {
#if (COMPILE_NAMES_SURFACES != 0)
	PASULI_SET_DESC("Plane", PLANE, descPlane),
	PASULI_SET_DESC("Agnesi Curl", BOHEMIAN_DOME_SURFACE, descBohemianDomeSurface),
	PASULI_SET_DESC("Astroidal Ellipsoid", ASTROIDAL_ELLIPSOID, descAstroidalEllipsoid),
	PASULI_SET_DESC("Balls Cylindroid", BALLS_CYLINDROID, descBallsCylindroid),
	PASULI_SET_DESC("Bell", BELL, descBell),
	PASULI_SET_DESC("Bell Polar", BELL_POLAR, descBellPolar),
	PASULI_SET_DESC("Bell Wave", BELL_WAVE, descBellWave),
	PASULI_SET_DESC("Bent Horns", BENT_HORNS, descBentHorns),
	PASULI_SET_DESC("Bicorn Surface", BICORN_SURFACE, descBicornSurface),
	PASULI_SET_DESC("Bohemian Dome Surface", BOHEMIAN_DOME_SURFACE, descBohemianDomeSurface),
	PASULI_SET_DESC("Bonan Jeener Klein Surface", BONAN_JEENER_KLEIN_SURFACE, descBonanJeenerKleinSurface),
	PASULI_SET_DESC("Bour's Minimal Surface", BOURS_MINIMAL_SURFACE, descBoursMinimalSurface),
	PASULI_SET_DESC("Bow Curve", BOW_CURVE, descBowCurve),
	PASULI_SET_DESC("Bowtie", BOWTIE, descBowtie),
	PASULI_SET_DESC("Boys Surface", BOYS_SURFACE, descBoysSurface),
	PASULI_SET_DESC("Boys Surface 2", BOYS_SURFACE2, descBoysSurface2),
	PASULI_SET_DESC("Bullet Nose", BULLET_NOSE, descBulletNose),
	PASULI_SET_DESC("Catalans Surface", CATALANS_SURFACE, descCatalansSurface),
	PASULI_SET_DESC("Catalans Surface 2", CATALANS_SURFACE, descCatalansSurface2),
	PASULI_SET_DESC("Catenoid", CATENOID, descCatenoid),
	PASULI_SET_DESC("Cayley Surface", CAYLEY_SURFACE, descCayleySurface),
	PASULI_SET_DESC("Cone", CONE, descCone),
	PASULI_SET_DESC("Cosine Surface", COSINE_SURFACE, descCosineSurface),
	PASULI_SET_DESC("Cosine Surface 2", COSINE_SURFACE2, descCosineSurface2),
	PASULI_SET_DESC("Cosine Wave", COSINE_WAVE, descCosineWave),
	PASULI_SET_DESC("Cresent", CRESENT, descCresent),
	PASULI_SET_DESC("Cross Cup", CROSS_CUP, descCrossCup),
	PASULI_SET_DESC("Cross Cup 2", CROSS_CUP2, descCrossCup2),
	PASULI_SET_DESC("Cross Cup 3", CROSS_CUP3, descCrossCup3),
	PASULI_SET_DESC("Crossed Trough Surface", CROSSED_TROUGH_SURFACE, descCrossedTroughSurface),
	PASULI_SET_DESC("Crown", CROWN, descCrown),
	PASULI_SET_DESC("Cuspidal Beaks", CUSPIDAL_BEAKS, descCuspidalBeaks),
	PASULI_SET_DESC("Curspidal Butterfly", CUSPIDAL_BUTTERFLY, descCuspidalButterfly),
	PASULI_SET_DESC("Cuspidal Edge", CUSPIDAL_EDGE, descCuspidalEdge),
	PASULI_SET_DESC("Cuspidal Lips", CUSPIDAL_LIPS, descCuspidalLips),
	PASULI_SET_DESC("Ding Dong Surface", DING_DONG_SURFACE, descDingDongSurface),
	PASULI_SET_DESC("Dini Surface", DINI_SURFACE, descDiniSurface),
	PASULI_SET_DESC("Disc", DISC, descDisc),
	PASULI_SET_DESC("Double Cone", DOUBLE_CONE, descDoubleCone),
	PASULI_SET_DESC("Drop", DROP, descDrop),
	PASULI_SET_DESC("Drop Surface", DROP_SURFACE, descDropSurface),
	PASULI_SET_DESC("Dupin Cyclide", DUPIN_CYCLIDE, descDupinCyclide),
	PASULI_SET_DESC("Egg", EGG, descEgg),
	PASULI_SET_DESC("Egg Surface", EGG_SURFACE, descEggSurface),
	PASULI_SET_DESC("Eight Surface", EIGHT_SURFACE, descEightSurface),
	PASULI_SET_DESC("Enneper Surface", ENNEPER_SURFACE, descEnneperSurface),
	PASULI_SET_DESC("Enneper Surface 2", ENNEPER_SURFACE2, descEnneperSurface2),
	PASULI_SET_DESC("Enneper Surface 3", ENNEPER_SURFACE3, descEnneperSurface3),
	PASULI_SET_DESC("Enneper Surface Polar", ENNEPER_SURFACE_POLAR, descEnneperSurfacePolar),
	PASULI_SET_DESC("Epitrochoidal Surface", EPITROCHOIDAL_SURFACE, descEpitrochoidalSurface),
	PASULI_SET_DESC("Facing Snail", FACING_SNAIL, descFacingSnail),
	PASULI_SET_DESC("Fish Surface", FISH_SURFACE, descFishSurface),
	PASULI_SET_DESC("Folium", FOLIUM, descFolium),
	PASULI_SET_DESC("Four Intersecting Discs", FOUR_INTERSECTING_DISCS, descFourIntersectingDiscs),
	PASULI_SET_DESC("Fresnel", FRESNEL, descFresnel),
	PASULI_SET_DESC("Funnel", FUNNEL, descFunnel),
	PASULI_SET_DESC("Goblet", GOBLET, descGoblet),
	PASULI_SET_DESC("Guimard Surface", GUIMARD_SURFACE, descGuimardSurface),
	PASULI_SET_DESC("Handkerchief", HANDKERCHIEF, descHandkerchief),
	PASULI_SET_DESC("Hector Guinards Surface", HECTOR_GUINARDS_SURFACE, descHectorGuinardsSurface),
	PASULI_SET_DESC("Helicoid", HELICOID, descHelicoid),
	PASULI_SET_DESC("Hennebergs Surface", HENNEBERGS_SURFACE, descHennebergsSurface),
	PASULI_SET_DESC("Hole Disc", HOLE_DISC, descHoleDisc),
	PASULI_SET_DESC("Hole Discus", HOLE_DISCUS, descHoleDiscus),
	PASULI_SET_DESC("Horn", HORN, descHorn),
	PASULI_SET_DESC("Hornlet Surface", HORNLET_SURFACE, descHornletSurface),
	PASULI_SET_DESC("Hyperbolic Helicoid", HYPERBOLIC_HELICOID, descHyperbolicHelicoid),
	PASULI_SET_DESC("Hyperbolic Octahedron", HYPERBOLIC_OCTAHEDRON, descHyperbolicOctahedron),
	PASULI_SET_DESC("Hyperbolic Paraboloid", HYPERBOLIC_PARABOLOID, descHyperbolicParaboloid),
	PASULI_SET_DESC("Hyperboloid", HYPERBOLOID, descHyperboloid),
	PASULI_SET_DESC("Isolator", ISOLATOR, descIsolator),
	PASULI_SET_DESC("Jeener Klein Surface", JEENER_KLEIN_SURFACE, descJeenerKleinSurface),
	PASULI_SET_DESC("Jet Surface", JET_SURFACE, descJetSurface),
	PASULI_SET_DESC("Kai Wing Fung Surface 1", KAI_WING_FUNG_SURFACE1, descKaiWingFungSurface1),
	PASULI_SET_DESC("Kai Wing Fung Surface 2", KAI_WING_FUNG_SURFACE2, descKaiWingFungSurface2),
	PASULI_SET_DESC("Kappa Surface", KAPPA_SURFACE, descKappaSurface),
	PASULI_SET_DESC("Kiss Surface", KISS_SURFACE, descKissSurface),
	PASULI_SET_DESC("Klein Bottle Surface", KLEIN_BOTTLE_SURFACE, descKleinBottleSurface),
	PASULI_SET_DESC("Klein Bottle Surface 2", KLEIN_BOTTLE_SURFACE2, descKleinBottleSurface2),
	PASULI_SET_DESC("Klein Cycloid", KLEIN_CYCLOID, descKleinCycloid),
	PASULI_SET_DESC("Kuens Surface", KUENS_SURFACE, descKuensSurface),
	PASULI_SET_DESC("Lawson Bottle", LAWSON_BOTTLE, descLawsonBottle),
	PASULI_SET_DESC("Lemniscape", LEMNISCAPE, descLemniscape),
	PASULI_SET_DESC("Loop", LOOP, descLoop),
	PASULI_SET_DESC("Maeders Owl", MAEDERS_OWL, descMaedersOwl),
	PASULI_SET_DESC("Menns Surface", MENNS_SURFACE, descMennsSurface),
	PASULI_SET_DESC("Milk Bag", MILK_BAG, descMilkBag),
	PASULI_SET_DESC("Moebius Band", MOEBIUS_BAND, descMoebiusBand),
	PASULI_SET_DESC("Moebius Band 2", MOEBIUS_BAND2, descMoebiusBand2),
	PASULI_SET_DESC("Moebius Band 3", MOEBIUS_BAND3, descMoebiusBand3),
	PASULI_SET_DESC("Monkey Saddle", MONKEY_SADDLE, descMonkeySaddle),
	PASULI_SET_DESC("Monkey Saddle 2", MONKEY_SADDLE2, descMonkeySaddle2),
	PASULI_SET_DESC("Morin Surface", MORIN_SURFACE, descMorinSurface),
	PASULI_SET_DESC("Neovius Surface", NEOVIUS_SURFACE, descNeoviusSurface),
	PASULI_SET_DESC("Paper Bag", PAPER_BAG, descPaperBag),
	PASULI_SET_DESC("Parabolic Humming Top", PARABOLIC_HUMMING_TOP, descParabolicHummingTop),
	PASULI_SET_DESC("Paraboloid", PARABOLOID, descParaboloid),
	PASULI_SET_DESC("Peano Surface", PEANO_SURFACE, descPeanoSurface),
	PASULI_SET_DESC("Peano Surface 2", PEANO_SURFACE2, descPeanoSurface2),
	PASULI_SET_DESC("Pillow Shape", PILLOW_SHAPE, descPillowShape),
	PASULI_SET_DESC("Piriform Surface", PIRIFORM_SURFACE, descPiriformSurface),
	PASULI_SET_DESC("Pisot Triaxial", PISOT_TRIAXIAL, descPisotTriaxial),
	PASULI_SET_DESC("Planar Enneper Surface", PLANAR_ENNEPER_SURFACE, descPlanarEnneperSurface),
	PASULI_SET_DESC("Pluecker Conoid", PLUECKER_CONOID, descPlueckerConoid),
	PASULI_SET_DESC("Pluecker Conoid 2", PLUECKER_CONOID2, descPlueckerConoid2),
	PASULI_SET_DESC("Pseudo Cross Cap", PSEUDO_CROSS_CAP, descPseudoCrossCap),
	PASULI_SET_DESC("Pseudodevelopable Helicoid", PSEUDODEVELOPABLE_HELICOID, descPseudodevelopableHelicoid),
	PASULI_SET_DESC("Richmond Surface", RICHMOND_SURFACE, descRichmondSurface),
	PASULI_SET_DESC("Richmond Surface 2", RICHMOND_SURFACE2, descRichmondSurface2),
	PASULI_SET_DESC("Richmond Surface 3", RICHMOND_SURFACE3, descRichmondSurface3),
	PASULI_SET_DESC("Roman Surface", ROMAN_SURFACE, descRomanSurface),
	PASULI_SET_DESC("Roman Surface 2", ROMAN_SURFACE2, descRomanSurface2),
	PASULI_SET_DESC("Ruled Rotor Cylindroid", RULED_ROTOR_CYLINDROID, descRuledRotorCylindroid),
	PASULI_SET_DESC("Scherk Surface", SCHERK_SURFACE, descScherkSurface),
	PASULI_SET_DESC("Scherk Surface 2", SCHERK_SURFACE2, descScherkSurface2),
	PASULI_SET_DESC("Shoe Surface", SHOE_SURFACE, descShoeSurface),
	PASULI_SET_DESC("Sievert Surface", SIEVERT_SURFACE, descSievertSurface),
	PASULI_SET_DESC("Sine Cone", SINE_CONE, descSineCone),
	PASULI_SET_DESC("Sine Cube", SINE_CUBE, descSineCube),
	PASULI_SET_DESC("Sine Surface", SINE_SURFACE, descSineSurface),
	PASULI_SET_DESC("Sine Wave", SINE_WAVE, descSineWave),
	PASULI_SET_DESC("Skidan Ruled Surface", SKIDAN_RULED_SURFACE, descSkidanRuledSurface),
	PASULI_SET_DESC("Snail 2", SNAIL2, descSnail2),
	PASULI_SET_DESC("Soucoupoid", SOUCOUPOID, descSoucoupoid),
	PASULI_SET_DESC("Spinner", SPINNER, descSpinner),
	PASULI_SET_DESC("Spinning Top 1", SPINNING_TOP1, descSpinningTop1),
	PASULI_SET_DESC("Spinning Top 2", SPINNING_TOP2, descSpinningTop2),
	PASULI_SET_DESC("Spiral Wave", SPIRAL_WAVE,descSpiralWave),	
	PASULI_SET_DESC("Spring1", SPRING1,descSpring1),
	PASULI_SET_DESC("Spring2", SPRING2,descSpring2),
	PASULI_SET_DESC("Steinbach Screw", STEINBACH_SCREW,descSteinbachScrew),
	PASULI_SET_DESC("Stiletto Surface", STILETTO_SURFACE,descStilettoSurface),
	PASULI_SET_DESC("Swallow Surface", SWALLOW_SURFACE,descSwallowSurface),
	PASULI_SET_DESC("Tooth Surface", TOOTH_SURFACE,descToothSurface),
	PASULI_SET_DESC("Tractroid", TRACTROID,descTractroid),	
	PASULI_SET_DESC("Tranguloid Trefoil", TRANGULOID_TREFOIL,descTranguloidTrefoil),
	PASULI_SET_DESC("Trashcan", TRASHCAN,descTrashcan),
	PASULI_SET_DESC("Trefoil Knots", TREFOIL_KNOTS,descTrefoilKnots),
	PASULI_SET_DESC("Trefoil Knots 2", TREFOIL_KNOTS2,descTrefoilKnots2),	
	PASULI_SET_DESC("Triaxial Hexatorus", TRIAXIAL_HEXATORUS,descTriaxialHexatorus),
	PASULI_SET_DESC("Triaxial Teardrop", TRIAXIAL_TEARDROP,descTriaxialTeardrop),	
	PASULI_SET_DESC("Triaxial Tritorus", TRIAXIAL_TRITORUS,descTriaxialTritorus),
	PASULI_SET_DESC("Triple Cork Screw 1", TRIPLE_CORK_SCREW1,descTripleCorkScrew1),
	PASULI_SET_DESC("Triple Cork Screw 2", TRIPLE_CORK_SCREW2,descTripleCorkScrew2),
	PASULI_SET_DESC("Triple Cork Screw 3", TRIPLE_CORK_SCREW3,descTripleCorkScrew3),
	PASULI_SET_DESC("Triple Point Twist", TRIPLE_POINT_TWIST,descTriplePointTwist),
	PASULI_SET_DESC("Twisted Heart", TWISTED_HEART,descTwistedHeart),	
	PASULI_SET_DESC("Twisted Pipe Surface", TWISTED_PIPE_SURFACE,descTwistedPipeSurface),	
	PASULI_SET_DESC("Twisted Ribbon", TWISTED_RIBBON,descTwistedRibbon),
	PASULI_SET_DESC("Umbrella Surface", UMBRELLA_SURFACE,descUmbrellaSurface),
	PASULI_SET_DESC("Vase Head", VASE_HEAD,descVaseHead),
	PASULI_SET_DESC("Verrill Surface", VERRILL_SURFACE,descVerrillSurface),
	PASULI_SET_DESC("Virich Cyclic Surface", VIRICH_CYCLIC_SURFACE,descVirichCyclicSurface),
	PASULI_SET_DESC("Wallis Conical Surface", WALLIS_CONICAL_SURFACE,descWallisConicalSurface),
	PASULI_SET_DESC("Waves", WAVES,descWaves),
	PASULI_SET_DESC("Wavy Enneper Surface", WAVY_ENNEPER_SURFACE,descWavyEnneperSurface),
	PASULI_SET_DESC("Whitney Umbrella", WHITNEY_UMBRELLA,descWhitneyUmbrella),
	PASULI_SET_DESC("Wreath",  WREATH,descWreath),	
	PASULI_SET_DESC("Zindlers Conoid", ZINDLERS_CONOID,descZindlersConoid),	
#endif
	/*
#if (COMPILE_NAMES_CYLINDER != 0)
	PASULI_SET_DESC("Cylinder", CYLINDER),
	PASULI_SET_DESC("Epizykloid Cylinder", EPIZYKLOID_CYLINDER),
	PASULI_SET_DESC("Hypozykloid Cylinder", HYPOZYKLOID_CYLINDER),
	PASULI_SET_DESC("Lemniskate Cylinder", LEMNISKATE_CYLINDER),
	PASULI_SET_DESC("Strophoide Cylinder", STROPHOIDE_CYLINDER),
	PASULI_SET_DESC("Zissoide Cylinder", ZISSOIDE_CYLINDER),
	PASULI_SET_DESC("Versiera Agnesi Cylinder", VERSIERA_AGNESI_CYLINDER),
	PASULI_SET_DESC("Gauss Cylinder", GAUSS_CYLINDER),
#endif
#if (COMPILE_NAMES_FRUITS != 0)
	PASULI_SET_DESC("Kidney Surface", KIDNEY_SURFACE),
	PASULI_SET_DESC("Apple Surface", APPLE_SURFACE),
	PASULI_SET_DESC("Apple Surface (2.nd Version)", APPLE2_SURFACE),
	PASULI_SET_DESC("Lemon Surface", LEMON_SURFACE),
#endif
#if (COMPILE_NAMES_SHELLS != 0)
	PASULI_SET_DESC("Cornucopia", CORNUCOPIA),
	PASULI_SET_DESC("Snail", SNAIL),
	PASULI_SET_DESC("Seashell", SEASHELL),
	PASULI_SET_DESC("Snail surface", SNAIL_SURFACE),
	PASULI_SET_DESC("Snails", SNAILS),
	PASULI_SET_DESC("Pseudoheliceras Subcatenatum", PSEUDOHELICERAS_SUBCATENATUM),
	PASULI_SET_DESC("Astroceras", ASTROCERAS),
	PASULI_SET_DESC("Bellerophina", BELLEROPHINA),
	PASULI_SET_DESC("Euhoplites", EUHOPLITES),
	PASULI_SET_DESC("Nautilus", NAUTILUS),
	PASULI_SET_DESC("Natica Stellata", NATICA_STELLATA),
	PASULI_SET_DESC("Mya Arenaria", MYA_ARENARIA),
#endif
#if (COMPILE_NAMES_SPHERE != 0)
	PASULI_SET_DESC("Sphere", SPHERE),
	PASULI_SET_DESC("Ellipsoid", ELLIPSOID),
	PASULI_SET_DESC("SphereV", SPHERE_V),
	PASULI_SET_DESC("SphereUV", SPHERE_UV),
	PASULI_SET_DESC("Pseudo-Sphere", PSEUDOSPHERE),
	PASULI_SET_DESC("Twisted Sphere", TWISTED_SPHERE),
	PASULI_SET_DESC("Open Sphere", OPEN_SPHERE),
	PASULI_SET_DESC("Wave Sphere", WAVE_SPHERE),
#endif
#if (COMPILE_NAMES_SPIRAL != 0)
	PASULI_SET_DESC("Archimedic Spiral", ARCHIMEDIC_SPIRAL),
	PASULI_SET_DESC("Hyperbolic Spiral", HYPERBOLIC_SPIRAL),
	PASULI_SET_DESC("Fermat Spiral", FERMAT_SPIRAL),
	PASULI_SET_DESC("Tanh Spiral", TANH_SPIRAL),
	PASULI_SET_DESC("Logarithmic Spiral", LOG_SPIRAL),
#endif
#if (COMPILE_NAMES_TORUS != 0)
	PASULI_SET_DESC("Torus", TORUS),
	PASULI_SET_DESC("Eight Torus", EIGHT_TORUS),
	PASULI_SET_DESC("Elliptic Torus", ELLIPTIC_TORUS),
	PASULI_SET_DESC("Saddle Torus", SADDLE_TORUS),
	PASULI_SET_DESC("Antisymmetric Torus", ANTISYMMETRIC_TORUS),
	PASULI_SET_DESC("Twisted Eight Torus", TWISTED_EIGHT_TORUS),
	PASULI_SET_DESC("Umbillic Torus", UMBILLIC_TORUS),
	PASULI_SET_DESC("Wave Torus", WAVE_TORUS),
	PASULI_SET_DESC("Braided Torus", BRAIDED_TORUS),
	PASULI_SET_DESC("Limpet Torus", LIMPET_TORUS),
	PASULI_SET_DESC("Strangled Torus", STRANGLED_TORUS),
	PASULI_SET_DESC("Astroid Torus", ASTROID_TORUS),
	PASULI_SET_DESC("Tricuspoid Torus 1", TRICUSPOID_TORUS_1),
	PASULI_SET_DESC("Tricuspoid Torus 2", TRICUSPOID_TORUS_2),
	PASULI_SET_DESC("Nephroid Torus 1", NEPHROID_TORUS_1),
	PASULI_SET_DESC("Nephroid Torus 2", NEPHROID_TORUS_2),
	PASULI_SET_DESC("Lemniskate Torus 1", LEMNISKATE_TORUS_1),
	PASULI_SET_DESC("Lemniskate Torus 2", LEMNISKATE_TORUS_2),
	PASULI_SET_DESC("Epizykloid Torus 1", EPIZYKLOID_TORUS_1),
	PASULI_SET_DESC("Epizykloid Torus 2", EPIZYKLOID_TORUS_2),
	PASULI_SET_DESC("Hypozykloid Torus 1", HYPOZYKLOID_TORUS_1),
	PASULI_SET_DESC("Hypozykloid Torus 2", HYPOZYKLOID_TORUS_2),
	PASULI_SET_DESC("Piriform Torus 1", PIRIFORM_TORUS_1),
	PASULI_SET_DESC("Piriform Torus 2", PIRIFORM_TORUS_2),
	PASULI_SET_DESC("Bicorn Torus 1", BICORN_TORUS_1),
	PASULI_SET_DESC("Bicorn Torus 2", BICORN_TORUS_2),
	PASULI_SET_DESC("Cardioid Torus 1", CARDIOID_TORUS_1),
	PASULI_SET_DESC("Cardioid Torus 2", CARDIOID_TORUS_2),
	PASULI_SET_DESC("Cassinian Oval Torus 1", CASSINIAN_OVAL_TORUS_1),
	PASULI_SET_DESC("Cassinian Oval Torus 2", CASSINIAN_OVAL_TORUS_2),
	PASULI_SET_DESC("Gerono-Lemniskate Torus 1", GERONO_LEMNISKATE_TORUS_1),
	PASULI_SET_DESC("Gerono-Lemniskate Torus 2", GERONO_LEMNISKATE_TORUS_2),
	PASULI_SET_DESC("Curly Torus 1", CURLY_TORUS_1),
	PASULI_SET_DESC("Curly Torus 2", CURLY_TORUS_2),
	PASULI_SET_DESC("Spiral Torus", SPIRAL_TORUS),
	PASULI_SET_DESC("Torus Knot", TORUS_KNOT),
	PASULI_SET_DESC("Gear Torus", GEAR_TORUS)
#endif
*/
};
/*
PASULI_PARSUR_STATIC PaSuLiTextDescType parsur_desc_array2[] = {
	
descPlane		//0
#if(COMPILE_DESC_SURFACES != 0)
,descBohemianDomeSurface
,descBoysSurface
,descCrossCup
,descDiniSurface
,descEnneperSurface
,descHandkerchief
,descKleinBottleSurface
,descMoebiusBand
,descMonkeySaddle

,descPlueckerConoid
,descRomanSurface
,descShoeSurface
,descSineSurface
,descSteinbachScrew
,descWhitneyUmbrella
,descCatenoid
,descHelicoid
,descParaboloid
,descHyperbolicHelicoid

,descFunnel
,descTractroid
,descCatalansSurface
,descHyperboloid
,descHennebergsSurface
,descSwallowSurface
,descWallisConicalSurface
,descMaedersOwl
,descRichmondSurface
,descScherkSurface

,descCosineSurface
,descEightSurface
,descJetSurface
,descDrop
,descTriaxialTeardrop
,descPillowShape
,descFishSurface
,descHorn
,descBentHorns
,descHyperbolicOctahedron

,descPseudoCrossCap
,descCresent
,descStilettoSurface
,descKuensSurface
,descTrefoilKnots
,descTranguloidTrefoil
,descCrown
,descTwistedPipeSurface
,descLoop
,descDupinCyclide

,descGuimardSurface
,descMennsSurface
,descMilkBag
,descTriaxialTritorus
,descVerrillSurface
,descZindlersConoid
,descFolium
,descLemniscape
,descTriplePointTwist
,descTrashcan

,descSpring1			//60
,descSpring2
,descCone
,descEgg
,descIsolator
,descHyperbolicParaboloid
,descDropSurface
,descFacingSnail
,descPaperBag
,descJeenerKleinSurface

,descBonanJeenerKleinSurface
,descKleinCycloid
,descDoubleCone
,descHoleDisc
,descPisotTriaxial
,descTriaxialHexatorus
,descTwistedHeart
,descHoleDiscus
,descDisc
,descWaves

,descSineWave
,descCosineWave
,descSpiralWave
,descBell
,descBellPolar
,descBellWave
,descSoucoupoid
,descEnneperSurfacePolar
,descSpinner
,descFresnel

,descTrefoilKnots2
,descBowCurve
,descTripleCorkScrew1
,descTripleCorkScrew2
,descTripleCorkScrew3
,descBicornSurface
,descPiriformSurface
,descKappaSurface
,descBulletNose
,descSievertSurface

,descCosineSurface2
#endif
//////////////////////////////////////
////////////  CYLINDER   /////////////
//////////////////////////////////////
#if(COMPILE_DESC_CYLINDER != 0)
,descCylinder			//101
,descEpizykloidCylinder
,descHypozykloidCylinder
,descLemniskateCylinder
,descStrophoideCylinder
,descZissoideCylinder
,descVersieraAgnesiCylinder
,descGaussCylinder
#endif
//////////////////////////////////////
////////////  FRUITS     /////////////
//////////////////////////////////////
#if(COMPILE_DESC_FRUITS != 0)
,descKidneySurface		//109
,descAppleSurface
,descApple2_Surface
,descLemonSurface
#endif
#if(COMPILE_DESC_SHELLS != 0)
,descCornucopia
,descSnail
,descSeashell
,descSnailSurface
,descSnails
,descPseudohelicerasSubcatenatum
,descAstroceras
,descBellerophina
,descEuhoplites
,descNautilus
,descNaticaStellata
,descMyaArenaria
#endif
//////////////////////////////////////
////////////  SPHERE     /////////////
//////////////////////////////////////
#if(COMPILE_DESC_SPHERE != 0)
,descSphere
,descEllipsoid
,descSphereV
,descSphereUV
,descPseudoSphere
,descTwistedSphere
,descOpenSphere
,descWaveSphere
#endif
//////////////////////////////////////
////////////  SPIRAL     /////////////
//////////////////////////////////////
#if(COMPILE_DESC_SPIRAL != 0)
,descArchimedicSpiral
,descHyperbolicSpiral
,descFermatSpiral
,descTanhSpiral
,descLogSpiral
#endif
#if(COMPILE_DESC_TORUS != 0)
,descTorus
,descEightTorus
,descEllipticTorus
,descSaddleTorus
,descAntisymmetricTorus
,descTwistedEightTorus
,descUmbillicTorus
,descWaveTorus
,descBraidedTorus
,descLimpetTorus
,descStrangledTorus
,descAstroidTorus
,descTricuspoidTorus1
,descTricuspoidTorus2

,descNephroidTorus1
,descNephroidTorus2
,descLemniskateTorus1
,descLemniskateTorus2
,descEpizykloidTorus1
,descEpizykloidTorus2
,descHypozykloidTorus1
,descHypozykloidTorus2
,descPiriformTorus1
,descPiriformTorus2

,descBicornTorus1
,descBicornTorus2
,descCardioidTorus1
,descCardioidTorus2
,descCassinianOvalTorus1
,descCassinianOvalTorus2
,descGeronoLemniskateTorus1
,descGeronoLemniskateTorus2
,descCurlyTorus1
,descCurlyTorus2

,descSpiralTorus
,descTorusKnot
,descGearTorus
#endif
};
*/

#undef PASULI_SET_TEXT_DESC

char *findDescriptionTextByID(unsigned char ID)
{
	const size_t numberOfEntries = sizeof(parsur_desc_array) / sizeof(PaSuLiTextDescType);
	if ((ID <= 0) || (ID > 255))
	{
		return 0;
	}

	for (size_t idx = 0; idx < numberOfEntries; idx++)
	{
		if (parsur_desc_array[idx].ID == ID)
		{
			char **ptr = parsur_desc_array[idx].pszDesc;

			if (ptr != 0)
			{
				return *ptr;
			}
		}
	}
	return 0;
}

void testDescriptionPointers()
{
	const size_t numberOfEntries = sizeof(parsur_desc_array) / sizeof(PaSuLiTextDescType);
	printf("#descriptions = %ld\n", numberOfEntries);
}

PASULI_PARSUR_STATIC PaSuLiDefDesc *parsur_def_desc_array[] = {
	/*
&pslddPlane		//0
#if(COMPILE_DEF_DESC_SURFACES != 0)
,&pslddBohemianDomeSurface		//1
,&pslddBoysSurface
,&pslddCrossCup
,&pslddDiniSurface
,&pslddEnneperSurface
,&pslddHandkerchief
,&pslddKleinBottleSurface
,&pslddMoebiusBand
,&pslddMonkeySaddle

,&pslddPlueckerConoid			//10
,&pslddRomanSurface
,&pslddShoeSurface
,&pslddSineSurface
,&pslddSteinbachScrew
,&pslddWhitneyUmbrella
,&pslddCatenoid
,&pslddHelicoid
,&pslddParaboloid
,&pslddHyperbolicHelicoid

,&pslddFunnel				//20
,&pslddTractroid
,&pslddCatalansSurface
,&pslddHyperboloid
,&pslddHennebergsSurface
,&pslddSwallowSurface
,&pslddWallisConicalSurface
,&pslddMaedersOwl
,&pslddRichmondSurface
,&pslddScherkSurface

,&pslddCosineSurface		//30
,&pslddEightSurface
,&pslddJetSurface
,&pslddDrop
,&pslddTriaxialTeardrop
,&pslddPillowShape
,&pslddFishSurface
,&pslddHorn
,&pslddBentHorns
,&pslddHyperbolicOctahedron

,&pslddPseudoCrossCap			//40
,&pslddCresent
,&pslddStilettoSurface
,&pslddKuensSurface
,&pslddTrefoilKnots
,&pslddTranguloidTrefoil
,&pslddCrown
,&pslddTwistedPipeSurface
,&pslddLoop
,&pslddDupinCyclide

,&pslddGuimardSurface			//50
,&pslddMennsSurface
,&pslddMilkBag
,&pslddTriaxialTritorus
,&pslddVerrillSurface
,&pslddZindlersConoid
,&pslddFolium
,&pslddLemniscape
,&pslddTriplePointTwist
,&pslddTrashcan

,&pslddSpring1			//60
,&pslddSpring2
,&pslddCone
,&pslddEgg
,&pslddIsolator
,&pslddHyperbolicParaboloid
,&pslddDropSurface
,&pslddFacingSnail
,&pslddPaperBag
,&pslddJeenerKleinSurface

,&pslddBonanJeenerKleinSurface	//70
,&pslddKleinCycloid
,&pslddDoubleCone
,&pslddHoleDisc
,&pslddPisotTriaxial
,&pslddTriaxialHexatorus
,&pslddTwistedHeart
,&pslddHoleDiscus
,&pslddDisc
,&pslddWaves

,&pslddSineWave				//80
,&pslddCosineWave
,&pslddSpiralWave
,&pslddBell
,&pslddBellPolar
,&pslddBellWave
,&pslddSoucoupoid
,&pslddEnneperSurfacePolar
,&pslddSpinner
,&pslddFresnel

,&pslddTrefoilKnots2			//90
,&pslddBowCurve
,&pslddTripleCorkScrew1
,&pslddTripleCorkScrew2
,&pslddTripleCorkScrew3
,&pslddBicornSurface
,&pslddPiriformSurface
,&pslddKappaSurface
,&pslddBulletNose
,&pslddSievertSurface

,&pslddCosineSurface2		//100
#endif
//////////////////////////////////////
////////////  CYLINDER   /////////////
//////////////////////////////////////
#if(COMPILE_DEF_DESC_CYLINDER != 0)
,&pslddCylinder			//101
,&pslddEpizykloidCylinder
,&pslddHypozykloidCylinder
,&pslddLemniskateCylinder
,&pslddStrophoideCylinder
,&pslddZissoideCylinder
,&pslddVACylinder
,&pslddGaussCylinder
#endif
//////////////////////////////////////
////////////  FRUITS     /////////////
//////////////////////////////////////
#if(COMPILE_DEF_DESC_FRUITS != 0)
,&pslddKidneySurface		//109
,&pslddAppleSurface
,&pslddApple2_Surface
,&pslddLemonSurface
#endif
#if(COMPILE_DEF_DESC_SHELLS != 0)
,&pslddCornucopia
,&pslddSnail
,&pslddSeashell
,&pslddSnailSurface
,&pslddSnails
,&pslddPseudohelicerasSubcatenatum
,&pslddAstroceras
,&pslddBellerophina
,&pslddEuhoplites
,&pslddNautilus
,&pslddNaticaStellata
,&pslddMyaArenaria
#endif
//////////////////////////////////////
////////////  SPHERE     /////////////
//////////////////////////////////////
#if(COMPILE_DEF_DESC_SPHERE != 0)
,&pslddSphere
,&pslddEllipsoid
,&pslddSphereV
,&pslddSphereUV
,&pslddPseudoSphere
,&pslddTwistedSphere
,&pslddOpenSphere
,&pslddWaveSphere
#endif
//////////////////////////////////////
////////////  SPIRAL     /////////////
//////////////////////////////////////
#if(COMPILE_DEF_DESC_SPIRAL != 0)
,&pslddArchimedicSpiral
,&pslddHyperbolicSpiral
,&pslddFermatSpiral
,&pslddTanhSpiral
,&pslddLogSpiral
#endif
#if(COMPILE_DEF_DESC_TORUS != 0)
,&pslddTorus
,&pslddEightTorus
,&pslddEllipticTorus
,&pslddSaddleTorus
,&pslddAntisymmetricTorus
,&pslddTwistedEightTorus
,&pslddUmbillicTorus
,&pslddWaveTorus
,&pslddBraidedTorus
,&pslddLimpetTorus
,&pslddStrangledTorus
,&pslddAstroidTorus
,&pslddTricuspoidTorus1
,&pslddTricuspoidTorus2

,&pslddNephroidTorus1
,&pslddNephroidTorus2
,&pslddLemniskateTorus1
,&pslddLemniskateTorus2
,&pslddEpizykloidTorus1
,&pslddEpizykloidTorus2
,&pslddHypozykloidTorus1
,&pslddHypozykloidTorus2
,&pslddPiriformTorus1
,&pslddPiriformTorus2

,&pslddBicornTorus1
,&pslddBicornTorus2
,&pslddCardioidTorus1
,&pslddCardioidTorus2
,&pslddCassinianOvalTorus1
,&pslddCassinianOvalTorus2
,&pslddGeronoLemniskateTorus1
,&pslddGeronoLemniskateTorus2
,&pslddCurlyTorus1
,&pslddCurlyTorus2

,&pslddSpiralTorus
,&pslddTorusKnot
,&pslddGearTorus
#endif
*/
};

PaSuLiDefDesc *findDescriptionByID(unsigned char ID)
{
	const size_t numberOfEntries = sizeof(parsur_def_desc_array) / sizeof(PaSuLiDefDesc *);
	if ((ID <= 0) || (ID > 255))
	{
		return 0;
	}

	for (size_t idx = 0; idx < numberOfEntries; idx++)
	{
		if (parsur_def_desc_array[idx]->ID == ID)
		{
			return parsur_def_desc_array[idx];
		}
	}
	return 0;
}
/*
pasuli_funcnum_range_type pasuli_cat_func_ranges[PASULI_CATEGORY_COUNT] = {
    PASULI_CAT_SURFACES_COUNT, //entries for SURFACES
    PASULI_CAT_CYLINDER_COUNT, //Cylinder
    PASULI_CAT_FRUIT_COUNT, //Fruits
    PASULI_CAT_SHELL_COUNT, //Shells
    PASULI_CAT_SPHERE_COUNT, //Sphere
    PASULI_CAT_SPIRAL_COUNT, //Spiral
    PASULI_CAT_TORUS_COUNT //Torus
};
*/
/*
pasuli_avail_info_type availablePaSuLiInfo[PASULI_CATEGORY_COUNT] = {
   
PASULI_SET_AVAILABLE(COMPILE_SURFACES, COMPILE_DEF_DESC_SURFACES, 
					COMPILE_DESC_SURFACES, COMPILE_NAMES_SURFACES)

,PASULI_SET_AVAILABLE(COMPILE_CYLINDER, COMPILE_DEF_DESC_CYLINDER, 
					COMPILE_DESC_CYLINDER, COMPILE_NAMES_CYLINDER)

,PASULI_SET_AVAILABLE(COMPILE_FRUITS, COMPILE_DEF_DESC_FRUITS, 
					COMPILE_DESC_FRUITS, COMPILE_NAMES_FRUITS)

,PASULI_SET_AVAILABLE(COMPILE_SHELLS, COMPILE_DEF_DESC_SHELLS, 
					COMPILE_DESC_SHELLS, COMPILE_NAMES_SHELLS)

,PASULI_SET_AVAILABLE(COMPILE_SPHERE, COMPILE_DEF_DESC_SPHERE, 
					COMPILE_DESC_SPHERE, COMPILE_NAMES_SPHERE)

,PASULI_SET_AVAILABLE(COMPILE_SPIRAL, COMPILE_DEF_DESC_SPIRAL, 
					COMPILE_DESC_SPIRAL, COMPILE_NAMES_SPIRAL)

,PASULI_SET_AVAILABLE(COMPILE_TORUS, COMPILE_DEF_DESC_TORUS, 
					COMPILE_DESC_TORUS, COMPILE_NAMES_TORUS)
					
};
*/