
#include <stdlib.h>
#include "pasuli_cfg.h"
#include "pasuli_repository.h"

unsigned int numberOfPasuli = 100;

typedef struct
{
	unsigned char id;
	double constant;
} DefaultConstants1;

typedef struct
{
	unsigned char id;
	double constants[2];
} DefaultConstants2;

typedef struct
{
	unsigned char id;
	double constants[3];
} DefaultConstants3;

typedef struct
{
	unsigned char id;
	double constants[4];
} DefaultConstants4;

#define PASULI_CONSTANT1_ENTRY(ID, C) \
	{                                 \
		ID, C                         \
	}
#define PASULI_CONSTANT2_ENTRY(ID, C1, C2) \
	{                                      \
		ID, { C1, C2 }                     \
	}
#define PASULI_CONSTANT3_ENTRY(ID, C1, C2, C3) \
	{                                          \
		ID, { C1, C2, C3 }                     \
	}

DefaultConstants1 forSingleConstant[] = {
	PASULI_CONSTANT1_ENTRY(PLANE, 0),

};

DefaultConstants2 for2Constants[] = {

};

DefaultConstants3 for3Constants[] = {

};

DefaultConstants4 for4Constants[] = {

};

#define ID_AND_LENGTH(ID, L) \
	{                        \
		ID, L                \
	}

#define CONST_1(C) C
#define CONST_2(C1, C2) C1, C2
#define CONST_3(C1, C2, C3) C1, C2, C3

unsigned char id_and_length[][2] = {
	ID_AND_LENGTH(PLANE, 1),
	ID_AND_LENGTH(BOHEMIAN_DOME_SURFACE, 3),
	ID_AND_LENGTH(BOYS_SURFACE, 0),
	ID_AND_LENGTH(CROSS_CUP, 0),
	//
	ID_AND_LENGTH(DINI_SURFACE, 2),
	ID_AND_LENGTH(ENNEPER_SURFACE, 0),
	ID_AND_LENGTH(HANDKERCHIEF, 0),
	ID_AND_LENGTH(KLEIN_BOTTLE_SURFACE, 3),
	//
	ID_AND_LENGTH(MOEBIUS_BAND, 1),
	ID_AND_LENGTH(MONKEY_SADDLE, 0),
	ID_AND_LENGTH(PLUECKER_CONOID, 0),
	ID_AND_LENGTH(ROMAN_SURFACE, 0),
	//
	ID_AND_LENGTH(SHOE_SURFACE, 0),
	ID_AND_LENGTH(SINE_SURFACE, 0),
	ID_AND_LENGTH(STEINBACH_SCREW, 0),
	ID_AND_LENGTH(WHITNEY_UMBRELLA, 0),
	//
	ID_AND_LENGTH(CATENOID, 1),
	ID_AND_LENGTH(HELICOID, 1),
};

float constants[] = {
	CONST_1(0),		  // PLANE
	CONST_3(1, 1, 1), // BOHEMIAN_DOME_SURFACE
	CONST_2(1, 0.2),  // DINI_SURFACE
	CONST_3(1, 1, 1), // KLEIN_BOTTLE_SURFACE
	CONST_1(1),		  // MOEBIUS_BAND
	CONST_1(1.5),	  // CATENOID
	CONST_1(1.5),	  // HELICOID
					  /*
	PARABOLOID,
	HYPERBOLIC_HELICOID,
	FUNNEL,
	TRACTROID,
	CATALANS_SURFACE,
	HYPERBOLOID,
	HENNEBERGS_SURFACE,
	SWALLOW_SURFACE,
	WALLIS_CONICAL_SURFACE,
	MAEDERS_OWL,
	RICHMOND_SURFACE,
	SCHERK_SURFACE,
	COSINE_SURFACE,
	EIGHT_SURFACE,
	JET_SURFACE,
	DROP,
	TRIAXIAL_TEARDROP,
	PILLOW_SHAPE,
	FISH_SURFACE,
	HORN,
	BENT_HORNS,
	HYPERBOLIC_OCTAHEDRON,
	PSEUDO_CROSS_CAP,
	CRESENT,
	STILETTO_SURFACE,
	KUENS_SURFACE,
	TREFOIL_KNOTS,
	TRANGULOID_TREFOIL,
	CROWN,
	TWISTED_PIPE_SURFACE,
	LOOP,
	DUPIN_CYCLIDE,
	GUIMARD_SURFACE,
	MENNS_SURFACE,
	MILK_BAG,
	TRIAXIAL_TRITORUS,
	VERRILL_SURFACE,
	ZINDLERS_CONOID,
	FOLIUM,
	LEMNISCAPE,
	TRIPLE_POINT_TWIST,
	TRASHCAN,
	SPRING1,
	SPRING2,
	CONE,
	EGG,
	ISOLATOR,
	HYPERBOLIC_PARABOLOID,
	DROP_SURFACE,
	FACING_SNAIL,
	PAPER_BAG,
	JEENER_KLEIN_SURFACE,
	BONAN_JEENER_KLEIN_SURFACE,
	KLEIN_CYCLOID,
	DOUBLE_CONE,
	HOLE_DISC,
	PISOT_TRIAXIAL,
	TRIAXIAL_HEXATORUS,
	TWISTED_HEART,
	HOLE_DISCUS,
	DISC,
	WAVES,
	SINE_WAVE,
	COSINE_WAVE,
	SPIRAL_WAVE,
	BELL,
	BELL_POLAR,
	BELL_WAVE,
	SOUCOUPOID,
	ENNEPER_SURFACE_POLAR,
	SPINNER,
	FRESNEL,
	TREFOIL_KNOTS2,
	BOW_CURVE,
	TRIPLE_CORK_SCREW1,
	TRIPLE_CORK_SCREW2,
	TRIPLE_CORK_SCREW3,
	BICORN_SURFACE,
	PIRIFORM_SURFACE,
	KAPPA_SURFACE,
	BULLET_NOSE,
	SIEVERT_SURFACE,
	COSINE_SURFACE2,
	PASULI_CAT_SURFACES_LAST = COSINE_SURFACE2

	// Cylinder
	,
	CYLINDER,
	PASULI_CAT_CYLINDER_FIRST = CYLINDER,
	EPIZYKLOID_CYLINDER,
	HYPOZYKLOID_CYLINDER,
	LEMNISKATE_CYLINDER,
	STROPHOIDE_CYLINDER,
	ZISSOIDE_CYLINDER,
	VERSIERA_AGNESI_CYLINDER,
	GAUSS_CYLINDER,
	PASULI_CAT_CYLINDER_LAST = GAUSS_CYLINDER
	//Fruits
	,
	KIDNEY_SURFACE,
	PASULI_CAT_FRUIT_FIRST = KIDNEY_SURFACE,
	APPLE_SURFACE,
	APPLE2_SURFACE,
	LEMON_SURFACE,
	PASULI_CAT_FRUIT_LAST = LEMON_SURFACE
	// Shells & snails
	,
	CORNUCOPIA,
	PASULI_CAT_SHELL_FIRST = CORNUCOPIA,
	SNAIL,
	SEASHELL,
	SNAIL_SURFACE,
	SNAILS,
	PSEUDOHELICERAS_SUBCATENATUM,
	ASTROCERAS,
	BELLEROPHINA,
	EUHOPLITES,
	NAUTILUS,
	NATICA_STELLATA,
	MYA_ARENARIA,
	PASULI_CAT_SHELL_LAST = MYA_ARENARIA
	// Spheres
	,
	SPHERE,
	PASULI_CAT_SPHERE_FIRST = SPHERE,
	ELLIPSOID,
	SPHERE_V,
	SPHERE_UV,
	PSEUDOSPHERE,
	TWISTED_SPHERE,
	OPEN_SPHERE,
	WAVE_SPHERE,
	PASULI_CAT_SPHERE_LAST = WAVE_SPHERE
	// Spirals
	,
	ARCHIMEDIC_SPIRAL,
	PASULI_CAT_SPIRAL_FIRST = ARCHIMEDIC_SPIRAL,
	HYPERBOLIC_SPIRAL,
	FERMAT_SPIRAL,
	TANH_SPIRAL,
	LOG_SPIRAL,
	PASULI_CAT_SPIRAL_LAST = LOG_SPIRAL
	// Torus
	,
	TORUS,
	PASULI_CAT_TORUS_FIRST = TORUS,
	EIGHT_TORUS,
	ELLIPTIC_TORUS,
	SADDLE_TORUS,
	ANTISYMMETRIC_TORUS,
	TWISTED_EIGHT_TORUS,
	UMBILLIC_TORUS,
	WAVE_TORUS,
	BRAIDED_TORUS,
	LIMPET_TORUS,
	STRANGLED_TORUS,
	ASTROID_TORUS,
	TRICUSPOID_TORUS_1,
	TRICUSPOID_TORUS_2,
	NETHROID_TORUS_1,
	NETHROID_TORUS_2,
	LEMNISKATE_TORUS_1,
	LEMNISKATE_TORUS_2,
	EPIZYKLOID_TORUS_1,
	EPIZYKLOID_TORUS_2,
	HYPOZYKLOID_TORUS_1,
	HYPOZYKLOID_TORUS_2,
	PIRIFORM_TORUS_1,
	PIRIFORM_TORUS_2,
	BICORN_TORUS_1,
	BICORN_TORUS_2,
	CARDIOID_TORUS_1,
	CARDIOID_TORUS_2,
	CASSINIAN_OVAL_TORUS_1,
	CASSINIAN_OVAL_TORUS_2,
	GERONO_LEMNISKATE_TORUS_1,
	GERONO_LEMNISKATE_TORUS_2,
	CURLY_TORUS_1,
	CURLY_TORUS_2,
	SPIRAL_TORUS,
	TORUS_KNOT,
	GEAR_TORUS,
	PASULI_CAT_TORUS_LAST = GEAR_TORUS,
	NUMB_OF_SURFACES
	*/
};

#undef CONST_1
#undef CONST_2
#undef CONST_3

#undef PASULI_CONSTANT1_ENTRY
#undef PASULI_CONSTANT2_ENTRY
#undef PASULI_CONSTANT3_ENTRY

#include <stdio.h>

int findDefaultConstants(unsigned int id, double *pConstants, int size)
{
	unsigned int alreadyDefined =
		sizeof(id_and_length) / (2 * sizeof(char));

	printf("#defined = %d\n", alreadyDefined);

	if (id >= 255)
	{
		return 0;
	}
	/*
    for (size_t i = 0; i < numberOfPasuli; i++)
    {
        if (repositoryItems[i].id == id)
        {
            return repositoryItems[i].pFunc;
        }
    }
    */
	return 0;
}