#ifndef __PASULI_TORUS_CONFIGURATION_HEADER_FILE_INCL__
#define __PASULI_TORUS_CONFIGURATION_HEADER_FILE_INCL__

#include "../pasuli_defs.h"

#define TORUS_NORMAL_VARS_DECL		PASULI_NORMAL_VARS_DECL

#define TORUS_NORMAL_VARS_DEF		PASULI_NORMAL_VARS_DEF

#define TORUS_NORMAL_VARS_COPY		PASULI_NORMAL_VARS_COPY

#define TORUS_NORMAL				PASULI_NORMAL

#define USE_PASULI_TORUS_TORUS		1
#define USE_PASULI_TORUS_TORUS_UA	0
#define USE_PASULI_TORUS_TORUS_VA	0
#define USE_PASULI_TORUS_TORUS_UVA	0

#define USE_PASULI_TORUS_ANTISYM_TORUS		1
#define USE_PASULI_TORUS_ANTISYM_TORUS_UA	0
#define USE_PASULI_TORUS_ANTISYM_TORUS_VA	0
#define USE_PASULI_TORUS_ANTISYM_TORUS_UVA	0

#endif

