#ifndef __PASULI_TORUS_ALL_INCLUDES__
#define __PASULI_TORUS_ALL_INCLUDES__

#include "antisym_torus.h"
#include "astroid_torus.h"
#include "bicorn_torus1.h"
#include "bicorn_torus2.h"
#include "braided_torus.h"
#include "cardioid_torus1.h"
#include "cardioid_torus2.h"
#include "cassinianoval_torus1.h"
#include "cassinianoval_torus2.h"
#include "curly_torus1.h"
#include "curly_torus2.h"
#include "elliptic_torus.h"
#include "epizykloid_torus1.h"
#include "epizykloid_torus2.h"
#include "gear_torus.h"
#include "geronolemniskate_torus1.h"
#include "geronolemniskate_torus2.h"
#include "hypozykloid_torus1.h"
#include "hypozykloid_torus2.h"
#include "lemniskate_torus1.h"
#include "lemniskate_torus2.h"
#include "limpet_torus.h"
#include "nethroid_torus1.h"
#include "nethroid_torus2.h"
#include "piriform_torus1.h"
#include "piriform_torus2.h"
#include "saddle_torus.h"
#include "spiral_torus.h"
#include "strangled_torus.h"
#include "torus.h"
#include "torus_knot.h"
#include "tricuspoid_torus1.h"
#include "tricuspoid_torus2.h"
#include "twisted_eight_torus.h"
#include "umbillic_torus.h"
#include "wave_torus.h"


#endif

