#ifndef __PASULI_COMPILATION_CONFIGURATION_FILE_NO_SURFACE_USED__
#define __PASULI_COMPILATION_CONFIGURATION_FILE_NO_SURFACE_USED__
////
// This file disables all surfaces
////
#define COMPILE_DEF_DESC_SURFACES 0
#define COMPILE_DESC_SURFACES 0

#define COMPILE_DEF_DESC_CYLINDER 0
#define COMPILE_DESC_CYLINDER 0

#define COMPILE_DEF_DESC_FRUITS 0
#define COMPILE_DESC_FRUITS 0

#define COMPILE_DEF_DESC_SHELLS 0
#define COMPILE_DESC_SHELLS 0

#define COMPILE_DEF_DESC_SPHERE 0
#define COMPILE_DESC_SPHERE 0

#define COMPILE_DEF_DESC_SPIRAL 0
#define COMPILE_DESC_SPIRAL 0

#define COMPILE_DEF_DESC_TORUS 0
#define COMPILE_DESC_TORUS 0

#define USE_PLANE 0
#define USE_ASTROIDAL_ELLIPSOID 0
#define USE_BOHEMIAN_DOME_SURFACE 0
#define USE_BOYS_SURFACE 0
#define USE_CROSS_CUP 0
#define USE_DINI_SURFACE 0
#define USE_ENNEPER_SURFACE 0
#define USE_HANDKERCHIEF 0
#define USE_KLEIN_BOTTLE_SURFACE 0
#define USE_MOEBIUS_BAND 0
#define USE_MOEBIUS_BAND2 0
#define USE_MONKEY_SADDLE 0
#define USE_PLUECKER_CONOID 0
#define USE_ROMAN_SURFACE 0
#define USE_SHOE_SURFACE 0
#define USE_SINE_SURFACE 0
#define USE_STEINBACH_SCREW 0
#define USE_WHITNEY_UMBRELLA 0
#define USE_CATENOID 0
#define USE_HELICOID 0
#define USE_PARABOLOID 0
#define USE_HYPERBOLIC_HELICOID 0
#define USE_FUNNEL 0
#define USE_TRACTROID 0
#define USE_CATALANS_SURFACE 0
#define USE_HYPERBOLOID 0
#define USE_HENNEBERGS_SURFACE 0
#define USE_SWALLOW_SURFACE 0
#define USE_WALLIS_CONICAL_SURFACE 0
#define USE_MAEDERS_OWL 0
#define USE_RICHMOND_SURFACE 0
#define USE_SCHERK_SURFACE 0
#define USE_COSINE_SURFACE 0
#define USE_EIGHT_SURFACE 0
#define USE_JET_SURFACE 0
#define USE_DROP 0
#define USE_TRIAXIAL_TEARDROP 0
#define USE_PILLOW_SHAPE 0
#define USE_FISH_SURFACE 0
#define USE_HORN 0
#define USE_BENT_HORNS 0

#define USE_BOURS_MINIMAL_SURFACE 0
#define USE_SINE_CUBE 0
#define USE_EGG_SURFACE 0
#define USE_WREATH 0

#define USE_HYPERBOLIC_OCTAHEDRON 0
#define USE_PSEUDO_CROSS_CAP 0
#define USE_CRESENT 0
#define USE_STILETTO_SURFACE 0
#define USE_KUENS_SURFACE 0
#define USE_TREFOIL_KNOTS 0
#define USE_TRANGULOID_TREFOIL 0
#define USE_CROWN 0
#define USE_TWISTED_PIPE_SURFACE 0
#define USE_LOOP 0
#define USE_DUPIN_CYCLIDE 0
#define USE_GUIMARD_SURFACE 0
#define USE_MENNS_SURFACE 0
#define USE_MILK_BAG 0
#define USE_SADDLE_TORUS 0
#define USE_TRIAXIAL_TRITORUS 0
#define USE_VERRILL_SURFACE 0
#define USE_ZINDLERS_CONOID 0
#define USE_FOLIUM 0
#define USE_LEMNISCAPE 0
#define USE_TRIPLE_POINT_TWIST 0
#define USE_TRASHCAN 0
#define USE_SPRING0 0
#define USE_SPRING2 0
#define USE_CONE 0
#define USE_EGG 0
#define USE_ISOLATOR 0
#define USE_HYPERBOLIC_PARABOLOID 0
#define USE_DROP_SURFACE 0
#define USE_FACING_SNAIL 0
#define USE_PAPER_BAG 0
#define USE_JEENER_KLEIN_SURFACE 0
#define USE_BONAN_JEENER_KLEIN_SURFACE 0
#define USE_KLEIN_CYCLOID 0
#define USE_DOUBLE_CONE 0
#define USE_HOLE_DISC 0
#define USE_PISOT_TRIAXIAL 0
#define USE_TRIAXIAL_HEXATORUS 0
#define USE_TWISTED_HEART 0
#define USE_HOLE_DISCUS 0
#define USE_DISC 0
#define USE_WAVES 0
#define USE_SINE_WAVE 0
#define USE_COSINE_WAVE 0
#define USE_SPIRAL_WAVE 0
#define USE_BELL 0
#define USE_BELL_POLAR 0
#define USE_BELL_WAVE 0
#define USE_SOUCOUPOID 0
#define USE_ENNEPER_SURFACE_POLAR 0
#define USE_SINE_CONE 0
#define USE_SPINNER 0
#define USE_FRESNEL 0
#define USE_TREFOIL_KNOTS2 0
#define USE_BOW_CURVE 0
#define USE_TRIPLE_CORK_SCREW0 0
#define USE_TRIPLE_CORK_SCREW2 0
#define USE_TRIPLE_CORK_SCREW3 0
#define USE_BICORN_SURFACE 0
#define USE_PIRIFORM_SURFACE 0
#define USE_KAPPA_SURFACE 0
#define USE_BULLET_NOSE 0
#define USE_SIEVERT_SURFACE 0
#define USE_COSINE_SURFACE2 0

//CYLINDER SURFACES
#define USE_CYLINDER 0
#define USE_EPIZYKLOID_CYLINDER 0
#define USE_HYPOZYKLOID_CYLINDER 0
#define USE_LEMNISKATE_CYLINDER 0
#define USE_STROPHOIDE_CYLINDER 0
#define USE_ZISSOIDE_CYLINDER 0
#define USE_VERSIERA_AGNESI_CYLINDER 0
#define USE_GAUSS_CYLINDER 0

//FRUITS SURFACES
#define USE_KIDNEY_SURFACE 0
#define USE_APPLE_SURFACE 0
#define USE_APPLE2_SURFACE 0
#define USE_LEMON_SURFACE 0

// Shells
#define USE_CORNUCOPIA 0
#define USE_SNAIL 0
#define USE_SEASHELL 0
#define USE_SNAIL_SURFACE 0
#define USE_SNAILS 0
#define USE_PSEUDOHELICERAS_SUBCATENATUM 0
#define USE_ASTROCERAS 0
#define USE_BELLEROPHINA 0
#define USE_EUHOPLITES 0
#define USE_NAUTILUS 0
#define USE_NATICA_STELLATA 0
#define USE_MYA_ARENARIA 0

// Sphere surfaces
#ifndef USE_SPHERE
#define USE_SPHERE 0
#endif

#ifndef USE_ELLIPSOID
#define USE_ELLIPSOID 0
#endif

#ifndef USE_SPHERE_V
#define USE_SPHERE_V 0
#endif

#ifndef USE_SPHERE_UV
#define USE_SPHERE_UV 0
#endif

#define USE_PSEUDOSPHERE 0
#define USE_TWISTED_SPHERE 0
#define USE_OPEN_SPHERE 0
#define USE_WAVE_SPHERE 0

// Spiral surfaces
#define USE_ARCHIMEDIC_SPIRAL 0
#define USE_HYPERBOLIC_SPIRAL 0
#define USE_FERMAT_SPIRAL 0
#define USE_TANH_SPIRAL 0
#define USE_LOG_SPIRAL 0

// TORUS SURFACES
#define USE_TORUS 0
#define USE_EIGHT_TORUS 0
#define USE_ELLIPTIC_TORUS 0
#define USE_SADDLE_TORUS 0
#define USE_ANTISYMMETRIC_TORUS 0
#define USE_TWISTED_EIGHT_TORUS 0
#define USE_UMBILLIC_TORUS 0
#define USE_BRAIDED_TORUS 0
#define USE_LIMPET_TORUS 0
#define USE_STRANGLED_TORUS 0
#define USE_ASTROID_TORUS 0
#define USE_TRICUSPOID_TORUS_0 0
#define USE_TRICUSPOID_TORUS_2 0
#define USE_NEPHROID_TORUS_0 0
#define USE_NEPHROID_TORUS_2 0
#define USE_LEMNISKATE_TORUS_0 0
#define USE_LEMNISKATE_TORUS_2 0
#define USE_EPIZYKLOID_TORUS_0 0
#define USE_EPIZYKLOID_TORUS_2 0
#define USE_HYPOZYKLOID_TORUS_0 0
#define USE_HYPOZYKLOID_TORUS_2 0
#define USE_PIRIFORM_TORUS_0 0
#define USE_PIRIFORM_TORUS_2 0
#define USE_BICORN_TORUS_0 0
#define USE_BICORN_TORUS_2 0
#define USE_CARDIOID_TORUS_0 0
#define USE_CARDIOID_TORUS_2 0
#define USE_CASSINIAN_OVAL_TORUS_0 0
#define USE_CASSINIAN_OVAL_TORUS_2 0
#define USE_GERONO_LEMNISKATE_TORUS_0 0
#define USE_GERONO_LEMNISKATE_TORUS_2 0
#define USE_CURLY_TORUS_0 0
#define USE_CURLY_TORUS_2 0
#define USE_SPIRAL_TORUS 0
#define USE_TORUS_KNOT 0
#define USE_GEAR_TORUS 0
#define USE_WAVE_TORUS 0

// New Ones
#define USE_ASTROIDAL_ELLIPSOID 0
#define USE_PEANO_SURFACE 0
#define USE_PEANO_SURFACE2 0
#define USE_UMBRELLA_SURFACE 0
#define USE_VASE_HEAD 0
#define USE_PLUECKER_CONOID2 0
#define USE_MONKEY_SADDLE2 0
#define USE_BOYS_SURFACE2 0
#define USE_SKIDAN_RULED_SURFACE 0
#define USE_SCHERK_SURFACE2 0
#define USE_CATALANS_SURFACE2 0
#define USE_WRINKLE_SPHERE 0
#define USE_WRINKLE_SPHERE2 0
#define USE_SNAIL2 0
#define USE_KLEIN_BOTTLE_SURFACE2 0
#define USE_FOUR_INTERSECTING_DISCS 0
#define USE_KAI_WING_FUNG_SURFACE0 0
#define USE_KAI_WING_FUNG_SURFACE2 0
#define USE_RICHMOND_SURFACE2 0
#define USE_RICHMOND_SURFACE3 0
#define USE_ENNEPER_SURFACE2 0
#define USE_ENNEPER_SURFACE3 0
#define USE_WAVY_ENNEPER_SURFACE 0
#define USE_TWISTED_RIBBON 0
#define USE_PLANAR_ENNEPER_SURFACE 0
#define USE_CAYLEY_SURFACE 0
#define USE_ROMAN_SURFACE2 0
#define USE_MOEBIUS_BAND3 0
#define USE_VIRICH_CYCLIC_SURFACE 0
#define USE_PSEUDODEVELOPABLE_HELICOID 0
#define USE_CROSS_CUP2 0
#define USE_CROSS_CUP3 0
#define USE_CUSPIDAL_BUTTERFLY 0
#define USE_CUSPIDAL_EDGE 0
#define USE_CUSPIDAL_LIPS 0
#define USE_CUSPIDAL_BEAKS 0
#define USE_DING_DONG_SURFACE 0
#define USE_TOOTH_SURFACE 0
#define USE_LAWSON_BOTTLE 0
#define USE_GOBLET 0
#define USE_BOWTIE 0
#define USE_HORNLET_SURFACE 0
#define USE_BALLS_CYLINDROID 0
#define USE_EPITROCHOIDAL_SURFACE 0
#define USE_MORIN_SURFACE 0
#define USE_CROSSED_TROUGH_SURFACE 0
#define USE_HECTOR_GUINARDS_SURFACE 0
#define USE_AGNESI_CURL 0
#define USE_SPINNING_TOP0 0
#define USE_SPINNING_TOP2 0
#define USE_KISS_SURFACE 0
#define USE_NEOVIUS_SURFACE 0
#define USE_RULED_ROTOR_CYLINDROID 0
#define USE_PARABOLIC_HUMMING_TOP 0

#endif
