#ifndef __FILE_UTILS_INCLUDED__
#define __FILE_UTILS_INCLUDED__

#ifndef READ_FILE_VERBOSE
#define READ_FILE_VERBOSE 1
#endif

#define READFILE_RESULT_SUCCESS 0

#define READFILE_RESULT_FILE_OPEN_FAIL 1
#define READFILE_RESULT_FILENAME_NULL 2
#define READFILE_RESULT_CONTENT_NULL 3
#define READFILE_RESULT_FILE_SEEK_FAIL 4
#define READFILE_RESULT_FILE_REWIND_FAIL 5
#define READFILE_RESULT_MEM_ALLOC_FAIL 6
#define READFILE_RESULT_FILE_READ_FAIL 7
#define READFILE_RESULT_FILE_CLOSE_FAIL 8

int readFile(char *pFilename, char **pContent, long *pSize);

#endif