#ifndef __PASULI_MESH_OPENGL__
#define __PASULI_MESH_OPENGL__

#include "pasuli_mesh.h"

#define PASULI_MESH_OPENGL_FILL 1
#define PASULI_MESH_OPENGL_NORMAL 2
#define PASULI_MESH_OPENGL_PARTIAL 4
#define PASULI_MESH_OPENGL_LINES_FROM_ORIGIN 0x8

#define PASULI_MESH_OPENGL_SURFACES_DEFAULT PASULI_MESH_OPENGL_FILL
#define PASULI_MESH_OPENGL_SURFACES_WITH_NORMALS PASULI_MESH_OPENGL_FILL|PASULI_MESH_OPENGL_NORMAL

void renderMesh(PaSuLiMesh* pMesh, int options);

#endif