#ifndef __PARAMETRIC_SURFACE_LIBRARY_FRUITS_CONFIGURATION__
#define __PARAMETRIC_SURFACE_LIBRARY_FRUITS_CONFIGURATION__

#define USE_PASULI_FRUITS_KIDNEY_SURFACE		1
#define USE_PASULI_FRUITS_KIDNEY_SURFACE_UA		1
#define USE_PASULI_FRUITS_KIDNEY_SURFACE_VA		1

/*
#define USE_PASULI_FRUITS_
#define USE_PASULI_FRUITS_
#define USE_PASULI_FRUITS_
*/

#endif

